import Head from 'next/head'
import Link from 'next/link'
import Layout from '../components/Layout'
import BlogList from '../components/BlogList'
import styles from '../styles/Home.module.css'

export default function Blog() {
  return (
    <div >
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by blog" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="canonical" href="https://snappyflow-test.surge.sh/blog" />
        <meta property="og:title" content="Snappyflow - Blog" />
        <meta property="og:type" content="Snappyflow - Blog" />
        <meta property="og:description" name="description" content="Blogs" />
        <meta property="og:url" content="/blog" key="ogurl" />
        <meta property="og:image" content="assets/images/add-application-screen.png" key="ogimage" />
      </Head>

      <Layout>
      <header id="blog-header">
        <div className="blog-intro">
          <div className="blog-overlay">
            <div className="container">
              <div className="row">
                <div className="intro-text">
                  <h1>Blogs</h1>
                </div>
              </div>
            </div>
          </div>
        </div>
      </header>
      <div className="container">
       <BlogList></BlogList>
      </div>
      <div className="sucessStoriesMain" id="sucessStoriesMain">
        <div className="container"> 
          <h4>Explore Case Studies</h4>
            <div className="clear">
                <div className="row">
                        <div className="col-md-4 col-xs-12">
                            <Link  className="parentAchor" 
                                  href="/case-study-new" 
                                    // (click)="focusTop()"
                                    >
                            <div className="card">
                              <img
                                className="card-img-top"
                                src="assets/images/case-study-01.png"
                                alt="Card image cap"
                              />
                              <div className="card-body new_card-body">
                                
                                <h5 className="card-title">SnappyFlow helps run a massive big data stack at peak performance</h5>
                                <div className="marginTop15">
                                Sustaining peak performance across multiple, hyperscale Hadoop clusters is no easy job, especially...
                                </div>
                                <div className="clear marginTop30">
                                  <Link className="view_button" 
                                  href="/case-study-new" 
                                    // (click)="focusTop()"
                                    >View Case Study 
                                  </Link>
                                </div>
                              </div>
                            </div>
                        </Link>
                          </div>
                          <div className="col-md-4 col-xs-12">
                            <Link   className="parentAchor" 
                                  href="/snappyflow-predictive-performance-kubernetes" 
                                    // (click)="focusTop()"
                                    >
                            <div className="card">
                              <img
                                className="card-img-top"
                                src="assets/images/case-study-02.png"
                                alt="Card image cap"
                              />
                              <div className="card-body new_card-body"> 
                                <h5 className="card-title">Predictive performance management of a Petabyte scale Kubernetes application for a Global Hi-Tech Major</h5>
                                <div className="marginTop15">
                                  SnappyFlow’s powerful Kubernetes monitoring capabilities helped troubleshoot...
                                </div>
                                <div className="clear marginTop30">
                                  <Link  className="view_button" 
                                  href="/snappyflow-predictive-performance-kubernetes" 
                                    // (click)="focusTop()"
                                    > View Case Study 
                                  </Link>
                                </div>
                              </div>
                            </div>
                        </Link>
                          </div> 
                </div>
            </div>
        </div>
      </div>
      <style jsx>
        {`
          .blog-intro {
            background: url("assets/images/blog_banner.jpg") no-repeat center center;
            background-size: 100%;
            width: 100%;
            position: relative;
          }
          
          .blog-intro h1 {
            color: #fff;
            text-shadow: 1px 1px 2px #363c44;
            text-align: left;
            /*margin-top: 0;*/
            /*margin-bottom: 10px;*/
            position: absolute;
            top: 29%;
            transform: translateY(-50%);
            font-size: 44px;
            letter-spacing: 0.44px;
            line-height: 1.36;
            /* font-family: montserrat, sans-serif; */
            font-weight: 700;
          }
          
          h4 {
            font-size: 14px;
            font-weight: bold;
            padding-bottom: 8px;
            letter-spacing: 0.5px;
          }
          p {
            font-size: 14px;
            padding-bottom: 20px;
            margin: 0px;
            line-height: 24px;
          }
          .about-img img {
            border: 1px solid #696969;
            box-shadow: 2px 5px 10px #ccc;
          }
          .border_section img {
            border-radius: 3px;
            cursor: pointer;
            margin-top: 15px;
          }
          .play_icon {
            position: absolute;
            top: 50%;
            left: 29%;
            transform: translate(-50%, -50%);
          }
          .para {
            width: 85%;
            text-align: justify;
            border-bottom: 1px solid #ddd;
            padding-bottom: 25px;
            line-height: 20px;
          }
          /*Common BLOG Section*/
          
          .commonBlog h3 {
            font-size: 32px;
            font-weight: bold;
          }
          .commonBlog .about-text {
            margin-left: 10px;
          }
          .commonBlog .about-img {
            display: inline-block;
            position: relative;
          }
          .commonBlog p {
            line-height: 16px;
            line-height: 24px;
            margin: 15px 0 30px;
          }
          .blog {
            padding: 120px 0;
          }
          .blog2 {
            padding: 120px 0;
            background-color: #cae9f6;
          }
          .blog-footer h2 {
            font-size: 24px;
            color: #009ece;
            text-transform: unset;
          }
          .sub {
            font-size: 18px;
            font-weight: 100;
            color: #363c44;
          }
          
          .emailInput {
            outline: none;
            padding: 0;
            margin: 0;
            width: 50%;
            border: none;
            /* border-radius: 25px 0 0 25px; */
            /* -webkit-border-radius: 25px 0 0 25px;
              -moz-border-radius: 25px 0 0 25px; */
            height: 40px;
            margin-bottom: 0;
            font-size: 18px;
            padding-left: 20px;
            font-weight: 400;
            border: 1px solid #ebebeb;
          }
          .errorMsg {
            color: #d4023c;
          }
          .txtMsg {
            transition: opacity 2s ease-in;
          }
          .subscibeButton {
            padding: 8px 20px;
            border-radius: 5px;
            border: solid 1px #b2b2b2;
            margin-left: 20px;
            outline: none;
            font-size: 15px;
            line-height: 18px;
            letter-spacing: 2px;
            /* font-weight: 600; */
            background: 0 0;
            transition: all 0.15s ease-in-out;
            transition-property: all;
            color: #009ece;
            float: none;
            text-transform: none;
          }
          
          .subscibeDiv {
            margin-top: 40px;
            margin-bottom: 65px;
          }
          .fontsize15 {
            font-size: 13px;
            margin-left: 13px;
          }
          .card {
            border-radius: 5px;
            box-shadow: 0 0 3px 0 rgba(0, 0, 0, 0.15);
            background-color: #ffffff;
            margin-bottom: 25px;
          }
          .coming_soon {
            font-size: 20px;
            color: #afafaf !important;
            border: 1px solid #ddd;
            text-align: center;
            line-height: 200px !important;
          }
          /* .card a img{
            width: 100%;
          } */
          /* .imgCardPlaceholder{
            height: 215px;
              width: 318px;
          } */
          .card-body h5 {
            font-size: 16px;
            font-weight: 600;
            font-stretch: normal;
            font-style: normal;
            margin-bottom: 15px;
            line-height: normal;
            letter-spacing: normal;
            text-align: left;
            color: #363c44;
            text-transform: unset;
          }
          .blog-intro .intro-text {
            padding: 0% 10% 10% 2%;
          }
          .card-body {
            padding: 30px;
            height: 180px;
          }
          .new_card-body{
            height: 220px !important
          }
          .card-body p {
            font-size: 16px;
            font-weight: normal;
            font-stretch: normal;
            font-style: normal;
            line-height: 1.56;
            letter-spacing: normal;
            text-align: left;
            color: #363c44;
            margin: 24px 0;
            /* opacity: 0.7; */
          }
          .card-img-top {
            width: 100%;
            border-radius: 5px 5px 0px 0px;
          }
          .card-body a {
            /* font-family: montserrat, sans-serif; */
            font-weight: 600;
            font-size: 14px;
            font-weight: 600;
            font-stretch: normal;
            font-style: normal;
            line-height: normal;
            letter-spacing: 0.16px;
            text-align: left;
            color: #17b7f1;
          }
          .img-arrow {
            margin-left: 10px;
          }
          .commonAbout {
            padding: 40px 0 45px 0;
          }
          .emailInput::placeholder {
            color: #363c44;
            opacity: 0.6;
          }
          .paddingTop21,
          .paddingTop21APM {
            padding-top: 21px;
          }
          .blog_heading h2 {
            font-size: 32px;
            color: #333;
            margin-bottom: 10px;
            /* font-family: montserrat, sans-serif; */
            font-weight: 700;
          }
          .post-meta {
            opacity: 0.7;
            padding-bottom: 12px;
          }
          .view_button{
            border: 1px solid #106585;
            border-radius: 40px;
            background: #fff;
            padding: 7px 20px;
            color: #106585 !important;
          }
          .post-meta{
            margin-bottom: 10px;
          }
          .sucessStoriesMain{
            padding:0px 15px 30px 15px;
          }
          .sucessStoriesMain h4{
            padding-bottom: 7px;
              position: relative;
              font-weight: 600;
              font-size: 18px;
              margin-bottom: 20px;
              text-transform: capitalize;
          }
          .card-title{
            margin-top: 0px;
          }
          .parentAchor{
            color: #000;
            cursor: pointer;
          }
          .parentAchor:hover{
            text-decoration: none;
            color: #000;
          }
          @media only screen and (min-width: 768px) and (max-width: 1199px) {
            .paddingTop21 {
              padding-top: 0 !important;
            }
          }
          @media only screen and (min-width: 320px) and (max-width: 767px) {
            .intro-text {
              padding: unset !important;
              position: unset;
              top: unset;
            }
            .intro-text h1 {
              font-size: 30px !important;
              line-height: 36px !important;
              left: 8% !important;
              top: 29% !important;
              width: 41% !important;
              text-align: left;
            }
            .emailInput {
              width: 48% !important;
            }
            .card-body h5 {
              font-size: 20px;
            }
            .blogheading h2 {
              font-size: 30px;
            }
          }
          @media screen and (max-width: 990px) and (min-width: 768px) {
            .card-body h5 {
              font-size: 20px;
            }
            .blogheading h2 {
              font-size: 30px;
            }
            header {
              margin-top: 56px !important;
            }
            .intro-text {
              padding: unset !important;
              position: unset;
              top: unset;
            }
            .intro-text h1 {
              font-size: 21px !important;
              line-height: 36px !important;
              left: 8% !important;
              top: 43% !important;
              width: 41% !important;
              text-align: left;
            }
            .blog-intro {
              position: relative !important;
              height: 243px !important;
            }
          }
          
        `}
      </style>
      </Layout>
    </div>
  )
}
