import Head from 'next/head'
import Link from 'next/link'
import Layout from '../components/Layout'

export default function Cookies() {
  return (
    <div className='cookies-page'>
      <Head>
        <title>Cookies</title>
        <meta name="description" content="Generated by suraj" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
      <div className="commonAbout about2">
        <div className="container">
            <div className="row">
            <div className="col-md-12 col-xs-12">
                <div className="center">
                    <h2>Cookie Policy</h2> 
                    </div>
                <div className="cookie-head">
                <h4>About Policy</h4>
                <p>The Cookie Policy (“Policy”) is applicable to MapleLabs Corporation (“MapleLabs”) online and mobile websites, applications, and digital services and clarifies data collection, usage and sharing practices among MapleLabs, its affiliates and unaffiliated third parties. You consent to the data collection, use, disclosure and storage practices described in this privacy policy when you browse our website (‘Site”) or use any of our website-based services,
        including when you access any content or videos on our websites (“Services”).</p>
                </div>
                <div className="cookie-head">
                <h4>Information Collected by us</h4>
                <p>We receive information that is both directly provided to us by you, such as personal information requested when you access the Services and information that is passively or automatically collected from you, such as anonymous information collected from your browser or device. In this Policy, we refer to all of this as the &quot;Information&quot;.
                </p>
                </div>
                <div className="cookie-head">
                <h4>Information Provided by user</h4>
                <p>You may be asked to provide your Information in order to access some of our Services. This includes registering for webinars, blog subscriptions and events, submitting an inquiry form, submitting your resume, subscribing to or accessing our online newsletters, blogs, whitepapers, brochures, webinars, podcasts, case studies or participating in one of our online forums. We may ask you for the following types of Information: name, address, e-mail address, telephone number, job title, organization name and country.</p>
                </div>
                <div className="cookie-head">
                <h4>Passively collected Information</h4>
                <p>A representative, non-exhaustive list of the types of automatically collected Information may include: referring sites, network or Internet protocol address and type of browser you are using (e.g., Chrome, Safari, Firefox, Internet Explorer), the type of operating system you are using, (e.g., Microsoft Windows or Mac OS), the name of your Internet service provider and domains used by such providers, mobile network, device identifiers (such as an Apple IDFA or an Android Advertising ID), device settings, browser settings, the webpages of the Services you have visited, webpages visited before and after you visit our Site, time spent on the Site, the type of handheld or mobile device used to view the Services (e.g., iOS, Android), language & location information, Interests, demographic information including age and gender, content and advertisements you have accessed, seen, forwarded and/or clicked on.</p>
                </div>
                <div className="cookie-head">
                <h4>Use of cookies and other technologies</h4>
                <p>Cookies are small, usually encrypted text files, which are used to perform various functions such as storing your preferences, allowing you to easily navigate between web pages, and improving overall user experience. These are located in browser directories and are useful since they have the ability to recognize a user’s PC or mobile device, and customize the user experience by transmitting small amounts of information back to the site. Cookies also help 3rd party agencies to collect information about user profiles, their interactions, actions, and behavior, which help site owners to improve components and functionalities available on the website. We do not collect personally identifiable information via cookies. The functionalities of some of our cookies that are processed via 3rd parties like Google Analytics, Visitor Track, Tawk.to, Twitter, LinkedIn, Facebook, SEMRush, Sharethis and Pardot are limited to providing us with web analytics and more detailed site activity information and intelligence about our website. Information collected via cookies on our website is anonymous and helps us improve our customer service.</p>
                </div>

                <div className="cookie-head">
                <h4>Deleting and blocking cookies</h4>
                <p>By using our website, you agree to provide us your explicit consent to the placement of cookies on your device, as explained above. In case you wish to remove these cookies from your device, you can delete these via your browser settings. You can also adjust your browser settings to block these cookies. However, please be informed that deleting or blocking cookies will adversely affect your user experience as certain parts of the website may stop functioning. User discretion is advised while deleting or blocking cookies.</p>
                <p>If you do not want to receive cookies from our website, you can disable them. In order to do so, please follow the relevant instruction depending on the type of your browser:</p>
                
                <ul>
                    <li>If you use  <a
                        href="https://support.microsoft.com/en-us/microsoft-edge/privacy-security-9459eef6-f8d8-4c6b-b3d5-d038e624da57"
                        target="_blank" rel="noreferrer">Microsoft Edge browser</a> </li>
                    <li>If you use <a href="https://support.google.com/chrome/?hl=en&amp;answer=95647#topic=7438008"
                        target="_blank" rel="noreferrer">Chrome browser</a></li>
                    <li>If you use <a href="https://support.mozilla.org/en-US/kb/enable-and-disable-cookies-website-preferences"
                        target="_blank" rel="noreferrer">Firefox browser</a> 
                    </li> 
                    <li>If you use  <a href="https://support.apple.com/en-in/guide/safari/sfri11471/mac" target="_blank" rel="noreferrer">Safari browser</a> </li>
                </ul>
                </div>
                <div className="cookie-head">
                <h4>Use of Information?</h4>
                <p>MapleLabs collects this information to make better business decisions towards our mutual advantage, support the activities you choose to engage in, and provide higher quality solutions and services to you and your customers. We will not sell, share, or rent this information, for commercial purposes, to any person or organization.</p>
                <ul className="order_list">
                    <li>To improve our website (we continually strive to improve our website offerings based on the information and feedback we receive from you)</li>
                    <li>To improve customer service (your information helps us to more effectively respond to your customer service requests and support needs),</li>
                    <li>Identify trends and statistics, which help us improve the services we offer to our customers</li>
                    <li>To share occasional company news, updates, related product or service information, etc</li>
                    <li>Fulfill your requests regarding the Services, including without limitation requests for newsletters and notifications</li>
                    <li>Respond to your inquiries</li>
                    <li>Communicate with you about other products, programs or services that we believe may be of interest to you</li>
                    <li>Provide technical support for the Services</li>
                    <li>Protect the safety of our Users</li>
                    <li>Perform analysis regarding how you use the Services or any part thereof</li>
                    <li>Invitations or emails if you use these services, to your designated recipients</li>
                    <li>Recruitment related purposes which may include contacting you via email, phone or post</li>
                </ul>
                </div>
                <div className="cookie-head">
                <h4>Information security</h4>
                <p>MapleLabs classifies your Information as Confidential Information. Confidential Information is protected by storing it on secure servers that only authorized MapleLabs personnel have access to. The information is encrypted to prevent unauthorized parties from accessing this information.</p>
                <p>Our website contains links to websites of third parties. MapleLabs has no control over, and is not responsible for, the content, privacy policies or reliability of such sites.</p>
                </div>
            
                <div className="cookie-head">
                <h4>Changes to the policy</h4>
                <p>MapleLabs reserves the right to modify or amend this Policy at its own discretion. This policy is effective from 1st Nov 2021. In order to check updates to this policy, please consult this page on a regular basis.</p>
                </div>
                <div className="cookie-head">
                <h4>Additional Information</h4>
                <p>If you would like to know more about MapleLabs’s Privacy program, please email us at <a href="mailto:maplelabsindia@maplelabs.com">maplelabsindia@maplelabs.com</a></p>
                </div>

            </div>

        </div>
        </div>
      </div>
        <style jsx>
            {`
                .container {
                    width: 1000px;
                }
                ul {
                  list-style: disc;
                  
                }
                li {
                  padding: 7px 0;
                  font-size:  16px;
                }
                .center{
                  text-align: center;
                  font-weight: bold;
                }                 
                .order_list{
                  padding:  0px;
                  margin:  0px 38px;
                }
                .order_list li{
                  list-style-type:  decimal;
                  font-size:  16px;
                }
                .center h2{
                    color: #009ece; 
                }
                .cookie-head h4{
                    text-transform: none;
                    font-weight: unset;
                    font-size: 20px;
                    padding-top: 15px;
                    padding-bottom: 10px;
                    font-family: Lato-Semibold;
                }
                .cookie-head{
                    margin-bottom: 20px;
                }
                h2{
                    padding-bottom: 50px;
                    text-transform:  capitalize;
                }
            `}
        </style>
      </Layout>
    </div>
  )
}
