import Head from 'next/head';
import Script from 'next/script';
import Layout from "../components/Layout";
import Link from "next/link";
import Slider from 'react-slick';

import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import { useEffect } from 'react';

var settings = {
  autoplay: true,
  autoplaySpeed: 3500,
  dots: false,
  infinite: true,
  speed: 600,
  pauseOnHover:true,
  slidesToShow: 1,
  adaptiveHeight: false
};

export default function Home() {
  return (
    <div>
      <Head>
        <title>Full Stack Monitoring Tracing Metrics Logs Profiling Alerts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="canonical" href="https://snappyflow-test.surge.sh/" />
        <meta property="og:title" content="Snappyflow" />
        <meta property="og:type" content="Snappyflow" />
        <meta property="og:description" name="description" content="Full Stack Monitoring Tracing Metrics Logs Profiling Alerts" />
        <meta property="og:url" content="/" key="ogurl" />
        <meta property="og:image" content="assets/images/add-application-screen.png" key="ogimage" />
      </Head>
      <Layout>
          <div className='indexPage'>
          <header id="header">
            <div className="intro indexDiv">
              <div className="overlay">
                <div className="container">
                  <div className="row">
                    <div className="intro-text container">
                      <div className="row">
                        <div className="col-md-7 col-xs-12 position_unset">
                          <div className="content">
                            <h1>Simplified Monitoring <br /><label>for</label> Complex Applications</h1>
                            <h5 className="sub_content">Achieve deep observability, strong correlation and improved resolution time of
                              your Cloud Native Applications.</h5>

                            <div className="tryItDiv"> <a href="https://snappyflow.io/freetrial" target="_blank" rel="noreferrer" className="free_trial_link"><input
                                  type="button" className="freeTrial_btn" value="TRY IT FOR FREE " name="" /></a></div>
                          </div>
                        </div>
                        <div className="col-md-5 col-xs-12 position_unset">
                          <div className="server_img_index"> </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </header>
          <div className="commonAbout about-odd">
            <div className="common_leftInnerContainer">
              <div className="container">
                <div className="row">
                  <div className="col-xs-12 mobile-about-text">
                    <h2>Improve Troubleshooting</h2>
                  </div>
                  <div className="col-xs-12 col-md-6 col-sm-7 padRight0 mobile-about-img">
                    <div className="about-img pull-right ">

                      <img src="assets/images/snappyflow-log-mgmt-img.png" className="img-responsive " alt="" />
                    </div>
                  </div>
                  <div className="col-xs-12 col-md-6 col-sm-5 left_10 padRight0 padLeft10 leftContent_section">
                    <div className="about-text">
                      <h2>Improve Troubleshooting</h2>
                      <div>
                        <div className="marTop15">
                          <ul className="disc_list">
                            <li>Comprehensive analysis of distributed microservices applications across VMs, Containers and Cloud
                              Services</li>
                            <li>Strong correlation across different elements of the stack</li>
                            <li>Superior Kubernetes monitoring with seamless infrastructure and application views</li>
                          </ul>
                        </div>
                        <div className="marTop25">
                          <a href="https://snappyflow.io/freetrial" target="_blank" rel="noreferrer" className="freetrial_link "> FREE TRIAL </a>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="col-xs-12 col-md-6 col-sm-7 padRight0 marTop50 desktop-img-wrapper">
                    <div className="about-img pull-right marTop5">
                      <img src="assets/images/improve-troubleshooting_1.png" className="dektop-img img-responsive" alt="" />
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div id="DistributedTracing"></div>

          </div>
          <div className="commonAbout about">
            <div className="common_rightInnerContainer">
              <div className="container">
                <div className="row">
                  <div className="col-xs-12 mobile-about-text">
                    <h2>Remove Islands of Monitoring</h2>
                  </div>
                  <div className="col-xs-12 col-md-6 col-sm-7 marTop50">
                    <div className="about-img left_20 marTop_5">
                      <img src="assets/images/remove_island.png" className="dektop-img img-responsive marTop25" alt="" />
                      <img src="assets/images/remove_island.png" className="img-responsive mobile-about-img" alt="" />
                    </div>
                  </div>
                  <div className="col-xs-12 col-md-6 col-sm-5 about-wrapper padRight0 rightContent_section">
                    <div className="about-text">
                      <h2>Remove Islands of Monitoring</h2>
                      <div className="marTop15">
                        <ul className="disc_list">
                          <li>Integrated workflow, including, Metrics, Log Management, Distributed Tracing, Synthetic Monitoring
                            and Alert Management</li>
                          <li>Cohesive functionality (vs running in silos) to enable powerful diagnostics</li>
                          <li>Seamless switching between features without leaving application context</li>
                        </ul>
                        <div className="marTop25">
                          <a href="https://snappyflow.io/freetrial" target="_blank" rel="noreferrer" className="freetrial_link "> FREE TRIAL </a>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div id="Intelligent"></div>
          </div>
          <div className="commonAbout about-odd">
            <div className="common_leftInnerContainer">
              <div className="container">
                <div className="row">
                  <div className="col-xs-12 mobile-about-text">
                    <h2>Log Management at Scale</h2>
                  </div>
                  <div className="col-xs-12 col-md-6 col-sm-7 padRight0  mobile-about-img marTop50">
                    <div className="about-img pull-right">
                      <img src="assets/images/log_management.png" className="img-responsive" alt="" />
                    </div>
                  </div>
                  <div className="col-xs-12 col-md-6 col-sm-5 left_10 padRight0 padLeft10 leftContent_section">
                    <div className="about-text">
                      <h2>Log Management at Scale</h2>
                      <div>
                        <div className="marTop15">
                          <ul className="disc_list">
                            <li>Powerful Search, Analytics and Parse-on-Ingest</li>
                            <li>10-40x compression on Archival with in-line search</li>
                            <li>Significant reduction in noise and clutter with Signatures feature</li>
                          </ul>
                        </div>
                        <div className="marTop25">
                          <a href="https://snappyflow.io/freetrial" target="_blank" rel="noreferrer" className="freetrial_link "> FREE TRIAL </a>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="col-xs-12 col-md-6 col-sm-7 padRight0 marTop25 desktop-img-wrapper">
                    <div className="about-img pull-right">
                      <img src="assets/images/log-management-sample-img2.png" className="dektop-img img-responsive marTop30" alt="" />
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div id="Application"></div>
          </div>

        <div className="commonAbout about-odd flex_banner marTop50 common_rightInnerContainer">
          <div className="container padLeft0 padRight0">
            <div className="about-text ">
              <h2>Tailored Consumption Model</h2>
            </div>
            <div className="clear row" style={{marginLeft: '-6px'}}>
              <div className="col-md-4 col-sm-12 col-xs-12 padRight10 modalHeader">
                <h3>SaaS</h3>
                <div className="piller">
                  <div>
                    <ul className="disc_list tick_list_Modal">
                      <li>SnappyFlow SaaS accessed via a simple and easy subscription</li>
                      <li>Optimize functionality per data needs</li>
                      <li>No infrastructure costs or maintenance</li>
                      <li>No software management</li>
                      <li>Usage-based Monthly Pricing</li>
                    </ul>
                  </div>
                </div>
              </div>

              <div className="col-md-4 col-sm-12 col-xs-12 padRight10 modalHeader">
                <h3>vAppliance*</h3>

                <div className="piller">
                  <div>
                    <ul className="disc_list tick_list_Modal vApplianceDiv">
                      <li>Available on AWS, Azure, GCP or vCenter</li>
                      <li>Easy setup and application onboarding</li>
                      <li>Automatic software updates</li>
                      <li>Flat Monthly or Annual Pricing</li>
                    </ul>
                  </div>

                </div>
              </div>

              <div className="col-md-4 col-sm-12 col-xs-12 padRight10 modalHeader">
                <h3>On-Prem SaaS</h3>

                <div className="piller">
                  <div>
                    <ul className="disc_list tick_list_Modal on_prem_saas_div">
                      <li>Complete SnappyFlow SaaS hosted and managed in your environment</li>
                      <li>Maintain full control of your data</li>
                      <li>Enterprise-level support</li>
                      <li>Flat Monthly or Annual Pricing</li>
                    </ul>
                  </div>
                </div>
              </div>
              <p className="marLeft20 noteDiv"><i style={{color: '#9e9e9e'}}>* Does not support Archival and Signature features in log management module</i>
              </p>
              <div className="marTop50 padLeft5 text-center learn_more_wrapper">
                <Link href="/pricing" className="freetrial_link " style={{padding: '10px 45px',
            borderRadius: '50px'}}> LEARN MORE </Link>
              </div>
            </div>

          </div>

        </div>
        <h3 className="text-center custom_heading marTop50 padTop20">What Our Customers Say</h3>
        
        <div className="testimonial">
          <div className="container">
            <div className="inner_container">
          

              <div className="clear" >
              <div className="carousel-inner carouselSlide">
              <Slider {...settings}>
                <div className="item">
                    <div className="row">
                        <div className="col-md-4 itm1">
                              <img src="assets/images/jombay-logo.png" />
                          </div>
                          <div className="col-md-8 ">
                            <div>
                              <p>While many monitoring tools did not have Kong monitoring out of the box, SnappyFlow came forward and custom-built a special module to help us monitor Kong API using SnappyFlow. With this feature, we can quickly identify API issues and resolve them to ensure a seamless customer experience.</p>
                              <p>The support from SnappyFlow team both in onboarding and building the custom module has been fantastic and I really appreciate their ability to quickly meet our unique needs in a very short span.</p>
                            </div>
                              <div className="padLeft10 padBottom20 modal-open">
                                <div className="col-md-2"><img src="assets/images/prashant_chaudhari.png" /></div>
                                <div className="sub_title col-md-10">
                                  <span className="fontStyle">Prashant Chaudhari</span>
                                  <div className="title_desc">Head of Engineering & Founding team member at Jombay</div>
                                </div>
                              </div>
                                
                          </div>
                    </div>
                </div> 
                <div className="item">
                    <div className="row">
                        <div className="col-md-4 itm1">
                              <img src="assets/images/exovion-logo.png" />
                          </div>
                          <div className="col-md-8 ">
                            <div>
                                <p className="positionRelative"> 
                              SnappyFlow, deployed in our production, has helped us <b>accelerate go-live and rollout</b> of our SaaS platform. Our applications are built on <b>.NET Core, AngularJS and Azure SQL technologies</b> using Azure App Services running on <b>Azure Cloud</b>. SnappyFlow’s <b>advanced application tracing</b>, metrics monitoring, and intuitive workflow have helped us <b>troubleshoot</b> faster and <b>reduce MTTR</b> significantly.
                              </p>
                              <p>Ezovion is an AI based SaaS healthcare platform transforming healthcare delivery across hundreds of Hospitals, Clinics, Labs, and Pharmacies to improve patient outcomes.</p>
                            </div>
                              <div className="padLeft10 padBottom20 modal-open">
                                <div className="col-md-2"><img src="assets/images/Kasiviswanathan.png" /></div>
                                <div className="sub_title col-md-10">
                                  <span className="fontStyle">Kasiviswanathan Shanmugam</span>
                                  <div className="title_desc">Managing Director</div>
                                </div>
                              </div>
                                
                          </div>
                    </div>
                </div> 
                <div className="item ">
                      <div className="row">
                          <div className="col-md-4">
                              <img src="assets/images/cavirin-logo.png" />
                          </div>
                          <div className="col-md-8">
                              <div>
                                <p > 
                                SnappyFlow gave us a view into our Kubernetes cluster and all the application pods running in the cluster.
                                It helped us root cause issues much faster and that makes SnappyFlow incredibly powerful. 
                              </p>
                              </div>
                              <div className="padLeft10 padBottom20 modal-open">
                                <div className="col-md-2"><img src="assets/images/Brajesh_Goyal.png" /></div>
                                <div className="sub_title col-md-10 " >
                                  <span className="fontStyle">Brajesh Goyal</span>
                                  <div className="title_desc">VP Engineering</div>
                                </div>
                              </div>
                            
                          </div>
                      </div>
                </div>
              </Slider>
              </div>
              </div> 
            </div>
          </div>
        </div>
          
          </div>
          {/* <div className="topText" onClick={scroll_Top}><button ><img
      src="assets/images/back-to-top-icon.png" /></button></div> */}
          <style jsx>
            {
              `
              .server_img_index{
                background: url(assets/images/home-page-banner.png) no-repeat;
                height: 460px;
                position: relative;
                top: -20px; 
              }
            
              header .indexDiv .intro-text, app-price .indexDiv .intro-text, app-products .indexDiv .intro-text {
                padding: 70px 0 13% 1%;
                text-align: center;
                font-size: 20px;
                /* background: url(Banner-white-shadow1.9522110….png) 100% 0 no-repeat #f8f8f8; */
                line-height: 34px;
                position: relative;
                top: 10px;
                height: 540px;
            }
            
            .freeTrial_btn, .freeTrial_btn:hover {
              background: #23b5e9;
              color: #fff;
              border-radius: 16px;
              border: 1px solid #045d7f;
              width: 160px;
              outline: 0;
              padding: 8px 15px;
              text-decoration: none;
              font-size: 12px;
              line-height: 15px;
            }
            
            .intro {
              /*background: url("../public/assets/images/bg_header.png") no-repeat center top;*/
              background: #f8f8f8; 
              width: 100%;
              height: 550px;
              position: relative;
            }
            .header-content-wrapper .col-md-1 {
              width: 40px;
            }
            
            .header-content-wrapper .col-md-2:hover svg g.cls-1,
            .header-content-wrapper .col-md-2:hover svg g.st0 {
              opacity: 0.15;
            }
            .header-content-wrapper .col-md-2:hover svg g.cls-1 path,
            .header-content-wrapper .col-md-2:hover svg g.st0 path {
              fill: #000;
            }
            /*.header-content-wrapper .col-md-2:nth-child(6):hover svg g{
              opacity: unset;
            }*/
            .header-content-wrapper .col-md-2:hover,
            .header-content-wrapper .col-md-2:hover svg path,
            .header-content-wrapper .col-md-2:hover svg circle,
            .header-content-wrapper .col-md-2:hover svg rect{ 
              /*background-position: 0 100%; */
              background: #009ed1;
              fill: #fff;
            }
            .header-content-wrapper .col-md-2 svg {
              width: 84px;
              height: 80px;
              margin-bottom: 15px;
            }
            .header-content-wrapper .col-md-2:first-child:hover{
              border-radius: 10px 0px 0px 10px
            }
            .header-content-wrapper .col-md-2:last-child:hover{
              border-radius:  0px 10px 10px 0px;
            }
            .header-content-wrapper .col-md-2:hover h3.card-title{
              color: #fff !important;
            }
            .header-content-wrapper .col-md-2:hover .card-text{
              display: block !important;
            }
            .inner-card-text{
              font-size: 20px;
              text-align: center;
            }
            .positionUnset{
              position: unset;
            }
            .left_20 {
              left: -20px;
            }
            .left_10 {
              left: -10px;
            }
            .header-content-wrapper {
              position: relative;
              top: -220px;
              padding: 0px;
              margin-bottom: -225px; 
              background: #fff;
              display: inline-block;
              width: 100%;
              border-radius: 10px;
              box-shadow: 4.6px 5.9px 27px 0 rgba(50, 80, 103, 0.09);
            }
            
            .header-content-wrapper .tab:last-child {
              margin-right: 0px;
            }
            .card-text {
              white-space: normal;
              font-size: 30px;
              color: #009dd0; 
              margin-top: 18px;
              display: none;
              /* font-family: montserrat, sans-serif; */
               font-weight: 600;
              position: absolute;
              margin-top: 80px;
              left: 50%;
              transform: translateX(-50%);
              width: fit-content;
            
            }
            .tab {
              padding: 0px 15px;
              width: 14.281%;
            }
            
            h1 {
              font-size: 44px;
            }
            .card-title {
              /* font-family: montserrat, sans-serif; */
              margin-top: 16px;
              font-weight: 600;
            }
            .flex_banner h3 {
              font-size: 25px; 
              font-stretch: normal;
              line-height: normal; 
              text-align: left;
              color: #2a383b;
              font-weight: 700 !important;
            }
            /*.common_rightInnerContainer{
              background: linear-gradient(90deg, rgba(255,255,255,1) 26%, rgba(250,250,250,1) 40%);
            }
            .common_leftInnerContainer{
              background: linear-gradient(90deg, rgba(250,250,250,1) 26%, rgba(255,255,255,1) 40%);
            }
            .common_leftInnerContainer .container,
            .common_rightInnerContainer .container{
              background: #fff
            }*/
            .content {
             /* position: absolute;
              top: 25px;
              left: 0px;*/
              font-size: 44px; 
              /*width: 54%;*/
              padding-top:  7%;
              /* font-family: montserrat, sans-serif; */
              font-weight: 600;
              text-align: left;
            }
            .content h1{
              color: #2A383B;
              text-align: left;
              letter-spacing: 0.24px;
              /* font-family: montserrat, sans-serif; */
              font-weight: 700 !important;
              font-size: 48px;
            }
            .content h1 label{
              font-size: 48px;
              font-family: Lato-Light;
              font-weight: 300;
            }
            .content h5{
              color: #2A383B;
               /* font-family: montserrat, sans-serif; */
               font-weight: 500;
                font-size: 24px;
                margin-top: 15px;
                line-height: 34px;
                text-align: left;
                letter-spacing: 0.7px;
            }
            .content-header-inner {
              position: absolute;
              top: 18%;
              left: 0px;
              font-size: 30px;
              color: #363c44;
              letter-spacing: 0.9px;
            }
            .content-header-inner-h5 {
              position: absolute;
              top: 15%;
              left: 0px;
              font-size: 18px;
              font-weight: normal;
              font-stretch: normal;
              font-style: normal;
              line-height: normal;
              letter-spacing: 0.6px;
              text-align: left;
              color: #363c44;
              text-transform: none;
            }
            .card {
              padding: 41px 0px 0;
            }
            .scrollContent tab:last-child .header-content-inner {
              box-shadow: -12.8px 28px 52px 0 rgba(50, 80, 103, 0.09);
            }
            
            .header-content-inner {
              text-align: center;
              /*position: relative;*/
              height: 261px;
            }
            .about-text-team {
              height: 50px;
            }
            .paraText h3 {
              padding-bottom: 70px;
            }
            ul {
              list-style: disc;
              padding: 10px 20px;
            }
            .about-text ul li,.about-text-advantage ul li{
              font-size: 20px;
              line-height: 28px;
              padding: 0px 2px 18px 14px;
            }
            
            .banner_innerSection {
              position: relative;
              width: 100%;
              transform: translate(-50%, -50%);
              top: 50%;
              left: 50%;
            }
            .contentboxinner h4 {
              color: white;
              text-transform: capitalize;
              font-family: Roboto-Medium;
              font-size: 22px;
            }
            
            .contentboxinner img {
              width: 120px;
              height: 120px;
            }
            .about-text p {
              margin-bottom: 0px;
              /* font-family: montserrat, sans-serif; */
              font-weight: 400; 
              line-height: 24px;
              text-align: justify;
            }
            .about-text p.fontStyle{
              color: #2A383B;
              font-weight: 500; 
              line-height: 22px;
            }
            .about-text-h2 {
              text-align: center;
              margin: 135px 0;
            }
            
            .rightCircle {
              position: relative;
              right: -25px;
              padding-left: 0px;
            }
            .leftCircle {
              position: relative;
              left: -25px;
              padding-right: 0px;
            }
            /* .about-wrapper{
              margin: 70px 0;
            } */
            .headerText {
              text-transform: none;
            }
            .contentbox {
              /* background-color: white; */
              /* padding: 48px; */
              text-align: center;
              /* box-shadow: 0px 1px 17px #e2e2e2; */
              margin-top: 30px;
            }
            .about-header {
              padding: 35px;
              background-color: #387091;
              color: white;
            }
            .contentboxinner h2 {
              padding-bottom: 20px;
              font-weight: normal;
            }
            .contentboxinner p {
              padding-top: 20px;
            }
            .img-left {
              width: 85%;
              border-radius: 40px 0;
            }
            .img-right {
              width: 85%;
              border-radius: 0 40px;
            }
            /* .tick-img{
              height: 25px;
              width: 25px;
              margin: 7px 6px 0 -15px;
            } */
            .content-wrapper {
              display: flex;
            }
            .about-header-inner h2 {
              color: white;
              text-align: center;
              letter-spacing: 2px;
            }
            .about-header-inner h3 {
              color: white;
              text-align: center;
              letter-spacing: 1px;
              font-size: 26px;
            }
            .feedback-wrapper h2 {
              font-weight: normal;
              color: white;
              text-align: center;
              /*text-transform: capitalize;*/
            }
            .feedback-wrapper p {
              text-align: center;
              font-size: 19px;
              font-style: italic;
            } 
            .card-img-top {
              margin : auto auto 10px; 
            }
            .about-text-advantage ul{
              margin: auto;
              width: 41%;
              padding: 10px 0 10px 30px !important;
            }
            .pointerCursor{
              cursor: pointer;
            }
            .piller{ 
                border-top: 0px; 
                border-radius: 0px 0px 10px 10px;
                border-top: 0px;
            }
            .col-md-4.padRight10 h3{
                padding: 0px 2px 20px;
                margin: 0px;  
                position: relative; 
            
            }
            .piller_subList{
              padding: 10px 17px !important;
              margin: 0px;
            }
            .piller_subList li{
              list-style-type: circle;
              padding-bottom: 20px;
            }
            .piller div{
              padding: 0px 10px 5px 9px;
            }
            .piller ul {
                font-size: 20px;
                padding: 0px 10px 10px 10px;
                height: 330px;
            }
            .piller ul li {
              line-height: 25px;
              padding-bottom: 15px; 
            }
            
            .useer_bg{
              background: #2A383B; 
              color: #fff;
              padding: 10px 0px;
              text-align: center;
            }
            .userTrial{     
                padding: 15px;
                text-align: center;
                font-size: 18px;
                width: 58%;
                clear: both;
                left: 50%;
                position: relative;
                transform: translateX(-50%);
            }
            .userTrial a{
              color: #29acd5
            } 
            .leftArrow_icon {
              position: absolute;
              cursor: pointer;
              top: -40%;
              transform: translateY(-50%);
              box-shadow: 2.463px 3.152px 7px 0px rgba(50, 80, 103, 0.09);
              background-color: #f5f5f5;
              border: solid 1px rgba(1, 73, 98, 0.1);
              /* background: #f5f5f5; */
              z-index: 10;
              padding: 15px 22px;
              border-radius: 5px;
              color: #757575;
              /* display: none; */
            }
            
            .rightArrow_icon {
              box-shadow: 2.463px 3.152px 7px 0px rgba(50, 80, 103, 0.09);
              /* border-color: 1px solid rgb(1, 73, 98); */
              background-color: #f5f5f5;
              border: solid 1px rgba(1, 73, 98, 0.1);
              position: absolute;
              cursor: pointer;
              top: -40%;
              transform: translateY(-50%);
              /* background: #f5f5f5; */
              z-index: 10;
              padding: 15px 22px;
              border-radius: 5px;
              /* display: none; */
            }
            .scrollContent {
              display: inline-flex !important;
              position: relative;
              transition: left 0.3s;
              padding-bottom: 60px;
              margin-left: 18px;
            }
            .mobile-about-text {
              display: none;
            }
            .mobileSubHeader {
              display: none;
            }
            .mobile-about-img {
              display: none;
            }
            .server_img{
              background: transparent url('assets/images/home-page-banner.png') 0px 0px no-repeat;
              height: 460px;
              position: relative;
              top: -20px;
                /*right: 50px;*/
            }
            .position_unset{
              position: unset;
            }
            .testimonial {
               background: #fff url('assets/images/testi-background.png') 0px 5px no-repeat;
                   padding: 20px 10px;
                background-size: cover;
                height: 550px;
                color: #fff;
                text-align: center;
            }
            .testimonial h3 {
                font-size: 36px;
                padding: 40px 0px;
                color: #2a383b;
                /*background: #fafafa;*/
                font-weight: 700; 
                margin: 0px -15px;
            }
            .testimonial_bg{
               position: relative;
                margin-top: 270px;
            }
            .inner_container {
              /*width: 1000px;*/
              margin: 0px auto;
            }
            .inner_container .col-md-2.userIcon {
                 padding: 20px;
                background: #fff;
                border-top: 3px solid #23b5e9; 
            }
            .inner_container .col-md-7{
                background: rgb(243 243 243 / 90%);
                height: 205px;
                width: 80.4%;
                border-top: 3px solid #23b5e9;
            }
            .first_col_2{
              width: 3% !important
            }
            .testimonial .sub_title { 
                font-size: 14px;
                margin-top: 30px;
                text-align:  left;
                text-indent:  20px;
                color: #2a383b;
            }
            .testimonial .sub_title span  { 
               /* font-family: montserrat, sans-serif; */
              font-weight: 500;
            }
            .testimonial .sub_title div{
              font-weight: 400;
              font-size: 14px;
            }
            .testimonial p {
                  padding: 8px 25px;
                font-size: 20px; 
                text-align: left;
                color: #2a383b;
                width: 100%;
            }
            
            .top_qut{
              position: absolute;
              left: 16px;
              margin-top: -35px;
            }
            .topText{
                position: fixed;
                bottom: 100px;
                display: none;
                right: 27px;
                z-index: 100;
            }
            
            .img-integration{
                margin: 0px 0px 15px 0px;
                border-radius: 5px;
                box-shadow: 0 0 3px 0 rgba(0, 0, 0, 0.15);
                background-color: #ffffff;
            } 
            .about-img-border  {
                padding: 5px 8px;
            }
            .panel_width{ 
              border: 1px solid #ddd;
              box-shadow: 2px 2px 4px #e6e6e6;
              border-radius: 5px;
              margin-bottom: 30px;
              /* font-family: montserrat, sans-serif; */
               font-weight: 600;
            }
            .panel_width label{
              background: #fafafa;
              padding: 20px 20px 17px 20px;
              margin: 0px 20px 0px 0px;
              border-radius: 5px 0px 0px 5px;
              border-right: 1px solid #ddd;
            }
            .panel_width span{ 
              font-size: 15px;
            }
            .about-text-advantage .col-md-6:nth-child(2){
                position: relative;
                padding-top: 8%;
            }
            
            .freeTrial{
             width: 175px;
                border-radius: 25px;
                background: #009dd0;
                border: 1px solid #009dd0;
                font-size: 18px;
                color: #fff;
                line-height: 35px;
                text-align: center;
            }
            .about-text-advantage{
              position: relative;
              left: -10px;
              display: inline-block;
              width: 100%;
              padding-top: 30px;
              margin-bottom: 20px;
            }
            .free_trial_link{
              position: relative;
              top: 15px;
              /* font-family: montserrat, sans-serif;  */
              color: #009dd0;
              font-size: 16px;
            }
            .free_trial_link i{
                font-size: 18px;
                margin-left: 5px;
            }
            .commonAbout h2,
            .about-text h2,
            .custom_heading{
              /* font-family: montserrat, sans-serif; */
              font-weight: 700;
              color: #2A383B;
              margin-bottom: 30px;
              text-transform: unset;
              font-size: 36px;
            }
            .leftContent_section{ 
                /*background: #fafafa;*/
                padding-bottom: 72px;
                padding: 50px 40px 50px 22px !important;
                border-radius: 0px 15px 15px 0px;
            }
            .common_rightInnerContainer{
              background: #f7f7f7 !important
            }
            .rightContent_section{ 
                /*background: #fafafa;*/
                padding-bottom: 72px;
                padding: 50px 40px 50px 35px;
                border-radius: 15px 0px 0px 15px;
            } 
            .flex_banner h2{
              color: #2a383b;
              text-align: center;
              position: relative;
              top: -30px;
            }
             
            .about-text-advantage .col-md-4 .panel_content{
                padding: 40px 40px 40px 40px;
                font-weight: 500;
                height: 430px;
                border-radius: 2.5px;
                border-radius: 30px 0px 0px;
                box-shadow: 1px 2px 11px #dadada;
                background-color: #ffffff;
                border: 1px solid #ddd;
            }
            .about-text-advantage .col-md-4 .panel_content img{
              padding: 0px 0px 25px 0px; 
            }
            .panel_content p{
              font-style: italic;
              font-size: 20px;
              text-align: left;
            }
            .modalHeader h3{
              font-size: 28px;
            }
            .carousel-inner {
                position: relative;
                width: 98%;
                padding: 0px 50px;
                overflow: unset;
                /* left: 3%; */
            }
            .carousel-inner .item .col-md-4{
             width: 38%;
            }
            .carousel-inner .item .col-md-8{
                 width: 60%;
                padding-left: 35px;
                border-left: 1px solid #dfdfdf;
                /* height:  510px; */
            }
            .carousel-inner .item:first-child .col-md-4{
                position: relative;
                top: 25px;
               
            } 
            .itm1{
              top: 60px !important;
            }
            .carousel-control{
                /* height: 2px; */
                width: 3%;
            }
            .carousel-control.left,
            .carousel-control.right{
              background-image:  none!important;
            } 
            
            
            
            @media only screen and (min-width: 320px) and (max-width: 450px) {
              .testimonial .col-md-4 img{
                width:  100%;
              }
               .testimonial .menu-right{
                    right: -34px;
              }
            }
            @media only screen and (min-width: 320px) and (max-width: 767px) {
            .carousel-inner{
              padding:  0px 20px;
            }
            .item .col-md-8{
              padding-right:  0px;
            }
              .testimonial .menu-right{
                    right: -34px;
              }
              .carousel-inner .item .col-md-4{
                  width: auto;
                  top:  unset !important;
            }
            .carousel-inner .item .col-md-8{
                 width:auto;
                padding-left: unset;
                border-left: 0px;
            }
              .piller_box .text-center.marTop25{ 
               margin-top: 10px !important;
              }
              .about-text .marTop25{
                text-align: center;
              }
              .piller ul{
                  padding: 0px 0px 10px 10px;
              }
              .commonAbout h2 , .about-text h2 {
                /* font-size: 25px; */
                text-align: center;
              }
              .leftContent_section.left_10 {
                left: 0px !important
              }
              .rightContent_section,
              .leftContent_section{
                background: transparent;
                padding: 30px 0px !important;
              }
              .header-content-wrapper .col-md-2:first-child:hover,
              .header-content-wrapper .col-md-2:last-child:hover{
                border-radius: 0px;
              }
              .about-text-advantage .col-md-4  {
                padding: 0px 10px 0px 25px !important;
              }
              .header-content-wrapper,
              .header-content-wrapper:hover  {
                border-radius: 0px !important;
                box-shadow: none;
              }
              .panel_width{
                width: 100% !important;
                left: 0px !important;
              }
              .about-text-advantage ul{
                width: 95% !important
              }
              .commonAbout{
                padding: 30px 0 0px 0px !important;
              }
              .flex_banner{
                margin-top: 50px;
              }
              .intro{
                background-size: cover;
              }
              header .intro-text {
                padding: unset !important;
                position: unset;
                top: unset;
                /* margin-top: 592px !important; */
              }
              .intro-text .row{
                  margin: 0px;
              }
              
              .scrollContent {
                display: block !important;
              }
              .tab {
                width: 100%;
                padding: 10px 8px 0;
              }
              .header-content-wrapper {
                position: unset !important;
                top: unset !important;
                margin-bottom: unset !important;
                margin-top: 20px;
              }
              .mobile-about-text {
                display: block;
                padding-bottom: 30px;
                padding-left: 5% !important;
              }
              .desktop{
                display: none;
              }
              .integration_bg{
                margin-top: 30px;
              }
              .integration_bg .about-text h2{
                display: block !important;
                padding: 8px;
              }
              .userTrial{
                padding-top: 15px;
              }
              .userTrial a{
                margin-bottom: -10px;
                display: block;
              }
              .piller{
                height: auto !important;
                padding: 20px 20px 0px 20px !important;
                margin-bottom: 25px;
              }
              .piller ul,
              .piller ul li:last-child{
                padding-bottom: 0px !important;
              }
              .about-text h2,
              .content-header-inner,
              .content-header-inner-h5,
              .dektop-img,
              .desktop-img-wrapper {
                display: none;
              }
              .flex_banner .about-text h2{
                display: block;
                padding-bottom: 20px;
                top: 0px !important;
              }
              .integration_bg .container.padLeft0{
                padding-left: 20px !important;
                padding-right: 20px;
              }
              .content {
                font-size: 35px;
                line-height: 38px; 
                text-align: center;
                top: 12% !important;
                width: 100% !important; 
                padding: 0px 25px;
                /* font-family: montserrat, sans-serif; */
                font-weight: 600;
                text-align: left;
              }
              .content h1,.content h5{
                text-align: center;
              }
              .mobileSubHeader {
                display: block;
              }
              .content-header-inner-mobile {
                /* margin-top:-15px; */
                left: 14px;
                font-size: 22px;
                color: #363c44;
                letter-spacing: 0.66px;
              }
              .content-header-inner-h5-mobile {
                font-size: 14px;
                font-weight: normal;
                font-stretch: normal;
                font-style: normal;
                line-height: normal;
                letter-spacing: 0.42px;
                text-align: center;
                color: #363c44;
                text-transform: none;
                padding: 0px 74px;
              }
              /* .mobile-about-text h2 {
                font-size: 26px;
              } */
              .mobile-about-img {
                display: block;
              }
              .left_20 {
                left: unset;
              }
              .about-text ul {
                padding: 10px 29px !important;
              }
              .commonAbout {
                padding: 30px 0 !important;
              }
            
              .firstAbout {
                padding-top: 80px !important;
              }
              .card-text{
                position: unset !important; 
                margin-top: unset !important; 
                left: unset !important; 
                color: #fff !important;
                transform: unset !important; 
                font-size: 18px !important; 
                margin-top: 3px !important;
              }
              .about-text-advantage .col-md-4 .panel_content{
                margin-bottom: 30px;
              }
              .testimonial{
                background-position: 0px -8px;
                width: 100%;
                background-size: unset; 
                padding: 5px 10px;
                height: fit-content;
              }
               .flex_banner .container {
                padding: 0px 15px !important
              }
              .header-content-wrapper .col-md-2,
              .header-content-wrapper .col-md-2:hover{
                background: unset;
                padding-right: 15px;
                padding-left: 15px;
              }
              .piller_box{
                padding-right: 0px;
              }
              
               .header-content-wrapper .col-md-2 .header-content-inner{
                background-color: rgb(255, 255, 255);
                box-shadow: 9.235px 11.82px 54px 0px rgba(50, 80, 103, 0.09);
                border-radius: 10px;
                height: 70px;
               }
               .header-content-wrapper .col-md-2 .header-content-inner .card{
                padding: 10px 0px 0;
               }
               .header-content-wrapper .col-md-2 .header-content-inner .card svg{
                  width: 45px;
                  height: 50px;
                  position: relative;
                  left: 10px;
               }
               .header-content-wrapper .col-md-2 .header-content-inner .card svg,
               .header-content-wrapper .col-md-2 .header-content-inner .card .card-body{
                float: left;
               }
               .header-content-wrapper .col-md-2 .header-content-inner .card h3{
                font-size: 16px;
                position: relative;
                left: 21px;
                letter-spacing: 0.7px;
               }
              .header-content-wrapper .col-md-2 .header-content-inner:hover{
                background: #009ed1;
              }
              .about-text-advantage{
                left: 0 !important;
              }
              .about-text-advantage .col-md-4 .panel_content{
                height: unset; 
                padding: 45px 30px 30px 30px !important;
              }
              .about-text-advantage .col-md-4 .panel_content img {
                padding: 15px 0px 45px 20px;
              }
            
              .freeTrial_btn{
                margin-top: 20px;
                font-size: 15px;
              }
              .piller ul{
                height: auto;
              }
              .server_img {
                background-position: center 50%;
                background-size: 100%;
              }
              .noteDiv,.sub_title,.title_desc{
                font-size: 25px !important;
              }
              .freetrial_link {
                font-size: 15px;
              }
              .learn_more_wrapper{
                margin-top: 25px;
              }
              .inner_container .col-md-3 img{
                width: 150px;
              }
              .inner_container .col-md-7{
                width: 100% !important;
                height: fit-content !important;
              }
              .common_rightInnerContainer{
                padding: 30px 0 !important;
              }
            }
            @media only screen and (min-width: 768px) and (max-width: 990px) {
                .testimonial .menu-right{
                    right: -34px;
              }
              .testimonial{
                height:  auto;
              }
              .carousel-inner .item .col-md-4{
                  width: auto;
                  top:  unset !important;
            }
            .carousel-inner .item .col-md-8{
                 width:auto;
                padding-left: unset;
                border-left: 0px;
            }
            .testimonial .sub_title{
              text-align:  center;
              }
            }
            @media only screen and (min-width: 768px) and (max-width: 1200px) {
              .flex_banner .container {
                padding: 0px 15px !important
              }
              .piller{
                height: 540px !important;
              }
              .img-integration{
                max-width: 151px;
              }
              .content{
                top: 32% !important;
              }
              .intro{
                background-size: cover;
              }
              .scrollContent {
                display: block !important;
              }
              .tab {
                width: 33.333%;
                /*margin-top: 25px;*/
              }
              .header-content-wrapper {
                position: unset !important;
                top: unset !important;
                margin-bottom: unset !important;
            
              }
              .footer-copyright {
                left: unset !important;
              }
              
            }
              `
            }
          </style>
      </Layout>
    </div>
  )
}
