import Head from 'next/head'
import Layout from '../components/Layout'

export default function Pricing() {
  return (
    <div className='pricing-page'>
      <Head>
        <title>Pricing</title>
        <meta name="description" content="Generated by suraj" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="canonical" href="https://snappyflow-test.surge.sh/pricing" />
        <meta property="og:title" content="Snappyflow - Pricing" />
        <meta property="og:type" content="Snappyflow- Pricing" />
        <meta property="og:description" name="description" content="Pricing" />
        <meta property="og:url" content="/pricing" key="ogurl" />
        <meta property="og:image" content="assets/images/add-application-screen.png" key="ogimage" />
      </Head>

      <Layout>
        {/* <main className={styles.main}> */}
        <header id="freetrial-header">
            <div className="price-intro indexDiv">
                <div className="freetrial-overlay">
                <div className="container">
                    <div className="row">
                    <div className="intro-text container">
                        <div className="row">
                        <div className="col-md-6 col-xs-12 position_unset ">
                            <div className="content">
                            <h1>Simple <label>and</label> <br /> Transparent pricing</h1>
                            <p>Get in touch with us at <a href="mailto:support@snappyflow.io">support@snappyflow.io</a> to get customized pricing to suit your unique needs.</p>
                            </div>
                        </div>
                        <div className="col-md-6 col-xs-12 position_unset">
                            <div className="server_img"> </div>
                        </div>
                        </div>
                    </div>
                    </div>
                
                </div>
                </div>
            </div> 
        </header>
        <div className="pricingHeadDiv">  
          <div className="container">
              <div className="text-center outerBox"  > 
                  {/* <h3>
                  Get in touch with us at <a href="mailto:support@snappyflow.io">support@snappyflow.io</a> to get customized pricing designed for your unique needs.
                  </h3> */}
              </div>
          </div> 
        </div>
        <style jsx>
          {`
            .pricing-table .col-md-12 .col-md-3{
              padding-right: 5px;
            } 
             
            #pricing-table {
              margin: 32px auto;
              /*text-align: center;*/
              width: 892px;
            }
            
            #pricing-table .plan { 
              text-shadow: 0 1px rgba(255,255,255,.8);        
              background: #fff;      
              color: #2A383B;
              padding: 20px;
              width: 297px; 
              float: left;
                position: relative;
                
            }
            
            /* .price-intro h1{ 
              color: #333;
                text-align: left;
                margin-top: 0;
                margin-bottom: 10px;
                position: absolute;
                top: 20%;
                font-size: 44px;
                letter-spacing: 0.44px;
                line-height: 1.36; 
                font-weight: 700;
                transform: translateY(-50%);
            } */
            .pricing-note h2{
              margin: 22px 10px 15px 10px;
            }
            #pricing-table #most-popular {
              z-index: 2;
              top: -13px;
              border-width: 3px;
              padding: 30px 20px;
              
            }
            .table{  
                border: 1px solid #cecdcd;  
                border-collapse: unset;
                margin-bottom: 5px;
                table-layout: fixed;
            } 
            .table tr th:first-child{
              /*border-radius: 10px 0px 0px 0px*/
            }
            .table tr th:last-child{
              /*border-radius: 0px 10px 0px 0px*/
            }
            .table tr th:nth-child(1),
            .table tr td:nth-child(1){
              /*text-align: center;*/
              width: 18%; 
              border-left: 0px !important;
              font-weight: 600;
            
            }
            /*.table tr td:nth-child(1){
              background: #f5f5f5;
              border-left: 1px solid #cecdcd; 
            }*/
            /*.table tr th:nth-child(4),
            .table tr td:nth-child(4){
              border-radius:4px;
            }
            */
            .verticalTop{
              vertical-align: top !important;
            }
            .table tr th{
              color: #fff;
              height: 50px;
              border-left:  1px solid #cecdcd !important;  
              border-bottom:  1px solid #cecdcd;
              border-right: 0px !important;  
              /*background: #009ece;*/ 
              vertical-align: middle;
                  background: #009ECE;
              text-align: left; 
              /* font-family: montserrat, sans-serif; */
               font-weight: 500 !important;
              font-size: 16px;
              
            }
            .table tr:nth-child(even) td{
              background:#fdfdfd;
            }
            .table tbody tr:first-child td{
              border-top: 0px;
            }
            .table tr td{
              border: 0px;
              text-align: left;
              color: #2A383B;
              vertical-align: middle;
              font-size: 16px; 
              border-top: 1px solid #cecdcd;
              border-left:  1px solid #cecdcd;   
            }
            .table tr:last-child td{
              border-bottom: 0px;
            }
            .emptyTR{
                  line-height: 2px;
                background: #fff !important;
                border-right: 0px !important;
                border-left: 0px !important;
                height: 5px;
                padding: 0px !important
            }
            .comming_soon{
              text-align: center !important;
              width: 88%;
              border-top: 1px solid #cecdcd !important;  
            }
            /*.comming_soon div,
            .comming_soon_text{
              color: #9e9f9f !important;
            }*/
            .instrucution_items span{
              color: #2A383B;
            }
            sup{
              color: #71757b;
            
            }
            .priceColor sup{
              font-size: 14px;
            }
            h2{
              padding-top: 10px;
              font-size: 25px;
            }
            h4{
              color: #959595;
              font-size: 17px;
              text-transform: capitalize;
            }
            .list_infra{
              font-size: 13px;
              color: #2A383B;
              margin-left: 20px;
            }
            .list_infra li{
              padding: 10px 0px;
              letter-spacing: 0.3px;
            }
            /* --------------- */	
            ol.list_infra {
              padding: 0px 15px;
              margin: 0px;
              font-size: 14px;
            }
            ol.list_infra li{
              list-style-type:decimal;
              padding-left: 4px;
            }
            #pricing-table h3 {
              font-size: 20px;
              font-weight: normal;
              padding: 20px;
              margin: -20px -20px 0 -20px;
              background-color: #eee;
              color: #fff;
              
            }
            
            #pricing-table #most-popular h3 {
              background-color: #ddd;
              margin-top: -30px;
              padding-top: 30px;
            }
            #pricing-table h3 span {
              display: block;
              font: bold 25px/100px Georgia, Serif;
              color: #777;
              background: #fff;
              border: 5px solid #fff;
              height: 100px;
              width: 100px;
              margin: 10px auto -65px;
            }
            
            /* --------------- */
            
            #pricing-table ul {
              margin: 6px 0 0 0;
              padding: 0;
              list-style: none;
            }
            
            #pricing-table li {
                padding: 15px 0;
                height: 50px;
                line-height: 17px;
            }
            
            /* --------------- */
              
            #pricing-table .signup {
              position: relative;
              padding: 8px 20px;
              margin: 20px 0 0 0;  
              color: #fff;
              font: bold 14px Arial, Helvetica;
              text-transform: uppercase;
              text-decoration: none;
              display: inline-block;       
              background-color: #72ce3f;
              background-image: -moz-linear-gradient(#72ce3f, #62bc30);
              background-image: -webkit-gradient(linear, left top, left bottom, from(#72ce3f), to(#62bc30));    
              background-image: -webkit-linear-gradient(#72ce3f, #62bc30);
              background-image: -o-linear-gradient(#72ce3f, #62bc30);
              background-image: -ms-linear-gradient(#72ce3f, #62bc30);
              background-image: linear-gradient(#72ce3f, #62bc30);
            }
            
            
            
            /* --------------- */
            
            .clear:before, .clear:after {
              content:"";
              display:table
            }
            
            .clear:after {
              clear:both
            }
            
            .clear {
              zoom:1
            }
            
            .odd{
                background-color: #eee;
            }
            .pricingHeadDiv{
              text-align: center;
                margin: 0px 0 25px 0px  ;
            }
            .pricingHeadDiv h2{
              /* font-family: montserrat, sans-serif;  */
                  font-size: 23px;
                font-weight: 400;
              margin: 0px;
              text-transform: unset;
              line-height: 1.33;
              color: #000;
            }
            .pricingHeadDiv p{
              line-height: 3;
                color: #2A383B;
            }
            .pricingHeadSpan{
              margin-left: 10px;
                font-size: 25px;
                color: #2A383B;
                position: relative;
                top: -2px;
            }
            .logoImg{
              margin-top: -13px;
              height: 18px;
                margin-left: -65px;
            }
            .planHeader{
              background-color: #868eca !important;
              
            }
            .planHeader2{
              background-color: #50b097 !important;
            }
            .planHeader3{
              background-color: #1ab6eb !important;
            }
            .evaluationPlan{
              border-left: 4px solid #868eca;
              border-bottom: 4px solid #868eca;
            }
            #most-popular{
              border: 4px solid #50b097;
            }
            .customPlan{
              border-right: 4px solid #1ab6eb;
              border-bottom: 4px solid #1ab6eb;
            }
            .price-rate{ 
              padding: 0px 110px 120px 100px; 
            }
            .price-rate  .col-md-4{
              text-align: center;
            }
            .price-rateSpan{
              font-weight: bold;
                padding-left: 15px;
            }
            .planHeader p, .planHeader2 p,.planHeader3 p {
              padding-top: 16px;
            }
            .planHeader2 p{
              font-size: 50px;
                margin-bottom: 0;
            }
            table {
              border-collapse: collapse;
              width: 100%;
              }
              
              td, th {
              border: 1px solid #ccc;
              text-align: center;
              padding: 10px 15px !important;
              width:25%;
              font-size: 15px;
            
              color: #2A383B;
              }
              th {
                height: 50px;
                font-weight: normal;
                /* font-family: montserrat, sans-serif; */
                  font-weight: 600;
                font-size: 17px;
              }
              ul {
              list-style: disc;
                font-size: 15px;
                color: #2A383B;
                padding-left: 21px;
              }
              /* .inner-price{
                margin: 108px 0;
              } */
              thead {
                font-size: 16px;
              }
            
              /* .inner-price ul li{
                padding: 4px 0;
              } */
              .inner-price ul li{
                padding: 5px 2px
              }
              .price-wrapper h5{
              line-height: 29px;
                font-size: 18px;
                 color: #635f5f;
              /* font-family: Roboto-thin; */
              text-transform: none;
                font-weight: normal;
              }
              .price-wrapper{
              position: relative;
                top: 40px
              }
              .Price_card{
                  border-radius: 5px;
                border: solid 1px #efefef;
                background-color: #fafafa;
                margin-bottom: 30px;
                height: 460px;
                position: relative;
              }
             .price_title {
              text-align: center;
                height: 95px;
                top: 0px;
                padding: 13px; 
                position: relative;
                border-radius: 5px 5px 0px 0px;
                box-shadow: 0px 3px 2px 0 rgba(181, 181, 181, 0.09);
                background-color: #009ece;
            }
            .price_head{
              /* font-family: montserrat, sans-serif;  */
              font-size: 20px;
              font-weight: 600;
              color: #ffffff;
              
            }
            .price_days{ 
              font-size: 13px; 
              position: relative;	
              top: 10px;
              line-height: 1.25;
              color: #ffffff;
            }
            .price_days span{
              /* font-family: montserrat, sans-serif; */
                font-weight: 600;
            }
            .content_part{
               padding: 0px 10px 10px 30px;
                margin-top: 5px;
            }
            .content_part ul{
              padding: 0px;
              margin: 0px;
            }
            /* .content_part ul li:first-child{
              margin-bottom: 15px
            } */
            .content_part ul li{
              list-style-type: none;
              font-size: 15px;
              color: #2A383B; 
              padding: 13px 0px;
            }
            /*.content_part ul li span{
              text-decoration: line-through;
            }*/
            .instrucution_items{
              color: #7b7e82;
              font-size: 14px;
            }
            .instrucution_items ol li{
              list-style-type:decimal;
              line-height: 1.6;
            }
            .pricing-note h4{
              /* font-family: montserrat, sans-serif; */
                font-weight: 600;
              font-size: 16px;
              line-height: 1.71;
              color: #2A383B;
            }
            /*.pricing-table .col-md-3{
              width: 20%
            }*/
            .freeTrial{
               width: 130px;
                border-radius: 25px;
                background: #009dd0;
                 /* font-family: montserrat, sans-serif; */
                 font-weight: 400;
                border: 1px solid #009dd0;
                font-size: 15px;
                color: #fff;
                line-height: 22px;
                text-align: center;
            }
            .freeTrial_position{
              position: absolute;
                bottom: 23px; 
                left: 50%;
                transform: translateX(-50%);
            
            }
            .coming_soon{
              font-size: 20px;
              color: #afafaf !important;
              border: 1px solid #ddd;
              line-height: 200px !important; 
            }
            .outerBox{
              /* border: 1px solid #ddd; */
              padding: 0px 0px;
            }
            .price_sub_title{
              font-size: 25px !important;
               /* font-family: montserrat, sans-serif; */
                font-weight: 600;
                font-weight: normal !important;
            }
            .tabView{
              margin-top: 42px;
            }
            .tab_inner{
              padding: 20px 0px 0px 0px;
              text-align: left;
            }
            .tabView ul.nav{
              margin: 0px;
                border: 1px solid #ddd;
                border-radius: 5px;
                padding: 0px;
            }
            .tabView ul.nav li a{
              color: #009dd0;
            }
            .tabView ul.nav li:first-child a{
              border-radius: 5px 0px 0px 5px
            }
            .tabView ul.nav li:last-child a{
              border-radius: 0px 5px  5px  0px 
            }
            .tabView ul.nav li{
              border-right: 1px solid #ddd;
            }
            .tabView ul.nav li:hover a{
              background: transparent;
            }
            .tabView ul.nav li:last-child{
              border-right: 0px;
            }
            .tabView ul.nav li.active a{
              background: #009ece;
              color: #fff;
            }
            .tabView ul.nav li{
              width: 33.33%;
              float: left;
            }
            .priceHead{
              color: #009ece;
                margin-bottom: 0px;
                margin-right: 50px;
                margin-top: 0px;
                font-weight: 700;
                font-size: 30px;
            }
            .inner_para .disc_list li{
              font-size: 20px;
            }
            .list_price_tab{
              padding:  0px;
              margin: 0px; 
              float: left; 
            }
            .list_price_tab li{
              list-style-type: none;
              float: left;
              color: #2A383B; 
              border: 1px solid #23B5E9;
              cursor: pointer;
              background-color: #ffffff;
            } 
            .list_price_tab li:first-child{
              border-radius: 4px 0 0 4px;
            }
            
            .list_price_tab li:last-child{
              border-radius:  0 4px 4px 0;
            }
            .list_price_tab li.active{
              border: 1px solid #23B5E9;
            }
            .list_price_tab li.active label{ 
              color: #fff;
              background: #23B5E9;
              border-radius: 2px;
              
            }
            .list_price_tab li:last-child a label{
              border-right: 0px;
            }
            .list_price_tab li a label{
              width: 160px;
              margin: 0px;
              font-weight: 600; 
            }
            .list_price_tab li  a label{
              padding: 8px 15px 8px 15px;
            }
            .list_price_tab li a,
            .list_price_tab li label{
              font-weight: 300;
              color: #2A383B;
              cursor: pointer;
            }
            .list_price_tab input{
              width: unset;
              margin-left: 5px;
              margin-right: 5px;
            }
            .notes{ 
                padding: 10px 10px 20px 20px;
                margin-top: 10px;
                background: #f8fdff;
                border-radius: 0px;
                border: 1px solid #c3e1ed;
            }
            .price_model{
              font-size: 16px;
              padding: 0px 0px 0px 10px;
            }
            .price_details{
              /*background: #f8f8f8;*/
              overflow: hidden;
              padding: 5px 0px 5px 5px;
              border-radius: 3px;
              /*border: 1px solid #f1f1f1;*/
              margin-bottom: 5px;
            }
            .price_details .col-md-3:nth-child(1){
              padding-left: 0px !important;
              text-align: left;
            }
            .price_headingList{
              color: #71757b;
              font-size: 11px;
              text-align: center;
            }
            .price_headingList .col-md-3{
              padding-left: 0px;
                width: 20%;
                padding: 10px 0px;
                text-align: center;
            }
            .price_details .col-md-3{
              color: #2A383B;
                width: 20%;
                padding: 8px 0px;
                text-align: center; 
            }
            .price_active{
              color: #009ece !important;
            }
            .wid20{
              width: 20%;
            }
            
            .activeVersion{
              position: relative;
                top: 15px;
                left: 36%;
                transform: translateY(-50%);
            }
            
            /* radio buttons */
            .radioButtonDiv{
              text-align: center;
            
            }
            .radioButtonDiv [type="radio"]:checked,
            .radioButtonDiv [type="radio"]:not(:checked) {
                position: absolute;
                left: -9999px;
            }
            .radioButtonDiv [type="radio"]:checked + span,
            .radioButtonDiv [type="radio"]:not(:checked) + span
            {
                position: relative;
                padding-left: 0px;
                cursor: pointer;
                line-height: 18px;
              display: inline-block; 
              font-size: 17px;
            }
            .radioButtonDiv [type="radio"]:checked + span:before,
            .activeVersion .radioButtonDiv .active  [type="radio"]:checked + span:before{
                border: 1px solid #009ece;
                opacity: 0;
            }
            .radioButtonDiv [type="radio"]:checked + span:before,
            .radioButtonDiv [type="radio"]:not(:checked) + span:before {
                content: '';
                position: absolute;
                left: -4px;
                top: 2px;
                width: 13px;
                height: 13px;
                border: 1px solid #2A383B;
                border-radius: 100%;
                background: #fff;
                 opacity: 0;
            }
            .content p{
              font-weight:  normal;
              margin-top: 30px;
              width: 375px;
            }
             
             .active .radioButtonDiv [type="radio"]:checked + span:before{
                border: 1px solid #23B5E9;
                 opacity: 0;
            }
            .radioButtonDiv [type="radio"]:not(:checked) + span{
              color: #23B5E9;
              
            }
             
            .radioButtonDiv  li [type="radio"]:not(:checked){
              background-color: #FFFFFF;
            }
            .radioButtonDiv [type="radio"]:checked + span:after,
            .radioButtonDiv [type="radio"]:not(:checked) + span:after {
                content: '';
                width: 5px;
                height: 5px;
                position: absolute;
                top: 6px;
                left: 0px;
                background-color: #666;
                border-radius: 100%;
                -webkit-transition: all 0.2s ease;
                transition: all 0.2s ease;
                opacity: 0;
            }
            .radioButtonDiv  .active  [type="radio"]:checked + span:after,
            .radioButtonDiv  .active  [type="radio"]:not(:checked) + span:after{
                    background: #009ece;
                    opacity: 0;
            }
            .radioButtonDiv [type="radio"]:not(:checked) + span:before{
                border: 1px solid #616162;
            }
            .radioButtonDiv [type="radio"]:not(:checked) + span:after {
                opacity: 0;
                -webkit-transform: scale(0);
                transform: scale(0);
            }
            .radioButtonDiv [type="radio"]:checked + span:after {
                opacity: 1;
                -webkit-transform: scale(1);
                transform: scale(1);
            }  
            .saas_container{
              /* border: 1px solid #ddd;
              background: #fbfbfb; */
              overflow: hidden;
              /* padding: 25px 15px; */
              border-radius: 3px;
            }
            .price_saasHead{
              /* background: #009ece;
              color: #fff; */
              padding: 10px 20px;
              text-align: left;
              margin-bottom: 10px;
            }
            .price_innerSection{ 
                overflow: hidden;
                position: relative;
                left: 50%;
                text-align: left;
              transform: translateX(-50%);
              height: 500px;
            }
            .price_panel{
              padding: 15px;
              width: 47%;
                height: 460px;
                background: #FFFFFF 0% 0% no-repeat padding-box;
                box-shadow: 0px 0px 12px #00000029;
                border-radius: 2px;
                margin-top: 20px;
                margin-left: 12px;
            }
            .price_innerSection h5{
              font-size: 32px;
                font-weight: 700;
              margin: 24px 0px 12px 0px;
              color: #23B5E9;
            }
            .price_innerSection label{
              font-weight: normal;
              margin: 0px;
            }
            .price_innerSection .col-md-6:nth-child(1) .price_saasHead{
              border-radius: 5px 
            }
            .inner_para{
              padding: 0 20px 10px;
            }
            .price_innerSection .col-md-6:nth-child(2) .price_saasHead {
              border-radius: 5px
            }
            .priceHead{
              color: #009ece;
                margin-bottom: 0px;
                margin-right: 50px;
                margin-top: 0px;
                font-weight: 700;
                font-size: 30px;
            
            }
            
            .pricing_tick_list{
              margin: 0px;
              padding: 0px 10px 0px 23px !important;
              list-style-image: url(../public/assets/images/check-solid.svg) !important; 
              font-size: 20px;
              line-height: 28px;
              }
              
              .pricing_tick_list li{
              padding: 0px 0px 20px 10px;
              }
            .server_img{
              background: transparent url(assets/images/Calculator1.png) 55% 0px no-repeat;
                height: 400px; 
            }
            .content {
                font-size: 44px;
                padding-top: 8.2%;
                font-weight: 600;
                text-align: left;
            }
            .price-intro {
                background: #f8f8f8;
                width: 100%;
                height: 550px;
            }
            .content h1{
                color: #2A383B;
                text-align: left;
                letter-spacing: 0.24px;
              font-size: 48px;
            }
            .content h1 label{
                font-size: 48px;
              font-family: Lato-Light;
              font-weight: 300;
            }
            .position_unset{
              position: unset;
            }
            .price_saasHead label{
              font-size: 28px;
              font-family: Lato-Bold;
            }
            .priceColor{
              color: #23B5E9;
              font-size: 20px;
            }
            .price_header_tag{
              font-size: 21px;
            }
            .indexDiv .intro-text{ 
                text-align: center;
                font-size: 20px;
                line-height: 34px; 
                height: 538px;
            }
            .table tbody tr td:first-child,.priceTableBlackFont{
              font-family: Lato-Black;
            }
            
            @media screen and (max-width: 767px) and (min-width: 320px) {
              /*.list_price_tab li a label{
                width: 140px !important;
              }*/
              .price_saasHead{
                text-align: center;
              }
              .instrucution_items{
                padding-top: 30px;
              }
               .server_img {
                background-position: center -30px;
                background-size: cover;
              }
              td,th{
                padding:8px  !important;
              }
              /* .intro-text{
                padding: unset !important;
                position: unset;
                top: unset;
              } */
              .inner_para{
                padding: 0px;
              }
              .panel_price,
              .panel_price .col-xs-12{
                padding-right: 0px;
                padding-left: 0px;
              }
              .nav > li{
                border-bottom: 1px solid #ddd;
                width: 100% !important;
                border-radius: 0px !important;
              } 
              .nav > li a{
                border-radius: 0px !important;
              }
              /* .intro-text h1{
                    font-size: 32px !important;
                    line-height: 36px !important;
                    left: 8% !important;
                    top: 54% !important;
                    width: 90% !important;
                    text-align: left;
              } */
              .pricing-note{
                padding: 0px;
              }
              .pricing-note table{
                table-layout: fixed;
                margin-top: 25px;
              }
              .list_infra{ 
                margin: 0px;
                  padding-right: 0px;
              }
              .price_panel{
                width: 95%;
                height: auto;
                margin-left: 12px !important;
                margin-bottom: 12px !important;
              }
              .activeVersion{
                left: 54% !important;
                  position: relative;
                  transform: translateX(-50%);
              }
              .radioButtonDiv [type="radio"]:checked + span,
              .radioButtonDiv [type="radio"]:not(:checked) + span{
                font-size: 20px;
              }
              .price_innerSection h5{
                line-height: 50px;
              }
              .price_innerSection{
                height: unset;
              }
              .content{
                padding-top: 0px !important;
              }
            }
            @media screen and (max-width: 990px) and (min-width: 768px) {
              .list_infra{ 
                margin: 0px;
                  padding-right: 0px;
              }
              .pricing-note{
                padding: 0px;
              }
              .pricing-note table{
                table-layout: fixed;
                margin-top: 25px;
              }
              .panel_price,
              .panel_price .col-xs-12{
                padding-right: 0px
              }
              .nav > li{
                border-bottom: 1px solid #ddd;
                width: 100% !important;
                border-radius: 0px !important;
              } 
              header{
                    margin-top: 56px !important;
                }
              /* .intro-text{
                padding: unset !important;
                position: unset;
                top: unset;
              }
              .intro-text h1{
                font-size: 32px !important;
                    line-height: 36px !important;
                    left: 8% !important;
                    top: 54% !important;
                    width: 90% !important;
                    text-align: left;
              } */
              .price-intro{
                    position: relative !important;
                    height: 250px !important;
                background-size: unset !important;
                }
            }
          `}
        </style>

        {/* </main> */}
      </Layout>
    </div>
  )
}
