import Head from 'next/head'
import Image from 'next/image'
import Layout from '../components/Layout'
import styles from '../styles/Home.module.css'
import Link from "next/link";

export default function Product() {
  return (
    <div className='productPage'>
      <Head>
        <title>Product</title>
        <link rel="icon" href="/favicon.ico" />
        <link rel="canonical" href="https://snappyflow-test.surge.sh/product" />
        <meta property="og:title" content="Product" />
        <meta property="og:type" content="Product" />
        <meta property="og:description" name="description" content="Generated by" />
        <meta property="og:url" content="/product" key="ogurl" />
        <meta property="og:image" content="assets/images/add-application-screen.png" key="ogimage" />
      </Head>

      <Layout>
      <header id="freetrial-header">
        <div className="product-intro indexDiv">
          <div className="freetrial-overlay">
            <div className="container">
              <div className="row">
                <div className="intro-text container">
                  <div className="row">
                    <div className="col-md-7 col-xs-12 position_unset ">
                      <div className="content">
                        <h1>Deeper Observability <br /><label>for</label> Accurate Analysis</h1>
                        <h5 className="sub_content" style={{paddingRight: '90px'}}>Maximize productivity and efficiency with
                          SnappyFlow’s deep and comprehensive
                          observability features.</h5>

                        <div className="tryItDiv"> <Link href="/" className="free_trial_link"><input
                              type="button" className="freeTrial_btn" value="TRY IT FOR FREE " name="" /></Link></div>
                      </div>
                    </div>
                    <div className="col-md-5 col-xs-12 position_unset marTop25">
                      <div className="server_img_product"> </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </header>



{/* <!-- About Section 2--> */}
<div className="commonAbout ">
  <div className="container">
    <div className="row">
      <div className="col-xs-12 mobile-about-text">
        <h2>Metrics</h2>
      </div>
      <div className="col-xs-12 col-md-6 col-sm-7 padRight0 mobile-about-img">
        <div className="about-img pull-right ">

          <img src="assets/images/snappyflow-kubernetes-img.png" className="img-responsive " alt="" />
        </div>
      </div>
      <div className="col-xs-12 col-md-5 col-sm-4 about-wrapper">
        <div className="about-text">
          <h2>Metrics</h2>
          <ul className="disc_list">
            <li>Pre-built dashboards for wide suite of applications and infrastructure components </li>
            <li>Auto recommendation of dashboards that “snap-in” to an application</li>
            <li>Powerful correlation owing to SnappyFlow’s application centric design, including applications running
              across VM & Kubernetes environments</li>
          </ul>
        </div>
        <div className="marTop25">
          <Link href="/" className="freetrial_link "> FREE TRIAL </Link>
        </div>
      </div>
      <div className="col-xs-12 col-md-7 col-sm-8 about-img-wrapper ">
        <div className="about-img">
          <img src="assets/images/snappyflow-kubernetes-img.png"
            className="dektop-img img-responsive custom_img about-img_odd" alt="" />

        </div>
      </div>
    </div>
  </div>
</div>

{/* <!-- About Section 3 --> */}
<div className="commonAbout about-odd">
  <div className="container ">
    <div className="row">
      <div className="col-xs-12 mobile-about-text">
        <h2>Logs</h2>
      </div>
      <div className="col-xs-12 col-md-6 col-sm-7 padRight0 mobile-about-img">
        <div className="about-img pull-right ">

          <img src="assets/images/snappyflow-log-mgmt-img.png" className="img-responsive " alt="" />
        </div>
      </div>
      <div className="col-xs-12 col-md-7 col-sm-8 about-img-wrapper ">
        <div className="about-img">
          <img src="assets/images/snappyflow-log-mgmt-img.png"
            className="dektop-img img-responsive custom_img about-img_even" alt="" />

        </div>
      </div>
      <div className="col-xs-12 col-md-5 col-sm-4 about-wrapper">
        <div className="about-text" style={{marginTop: '23px'}}>
          <h2>Logs</h2>
          <ul className="disc_list">
            <li>​​Search and Analytics feature</li>
            <li>Parse and feature extraction on Ingest</li>
            <li>Log Signatures to hide or show or stop collection of specific logs</li>
            <li>Significantly reduce noise, improve triaging as well as reduce log storage costs</li>
            <li>Log Archival that provides 10-40x storage compression, inline search without needing to re-ingest from
              archives, and fast searches on large archives based on SnappyFlow’s innovative technology</li>
          </ul>
        </div>
        <div className="marTop25">
          <Link  href="/"  className="freetrial_link "> FREE TRIAL </Link>
        </div>
      </div>
    </div>
  </div>
</div>

{/* <!-- About Section 4 --> */}
<div className="commonAbout about">
  <div className="container">
    <div className="row">
      <div className="col-xs-12 mobile-about-text">
        <h2>Tracing</h2>
      </div>
      <div className="col-xs-12 col-md-6 col-sm-7 padRight0 mobile-about-img">
        <div className="about-img pull-right ">

          <img src="assets/images/snappyflow-tracing-img.png" className="img-responsive " alt="" />
        </div>
      </div>
      <div className="col-xs-12 col-md-5 col-sm-4 about-wrapper">
        <div className="about-text">
          <h2>Tracing</h2>
          <ul className="disc_list">
            <li>​Tracing of Java, Python and Node.js applications
            </li>
            <li>Open tracing compliant; integrated with Jaeger
            </li>
            <li>Optimized sampling and collection to minimize performance impact
            </li>
            <li>Support for both Synchronous and Asynchronous tracing, including support for custom tagging
            </li>

          </ul>
        </div>
        <div className="marTop25">
          <Link href="/"  className="freetrial_link "> FREE TRIAL </Link>
        </div>
      </div>
      <div className="col-xs-12 col-md-7 col-sm-8 about-img-wrapper">
        <div className="about-img" style={{marginTop: "-6px"}}>
          <img src="assets/images/snappyflow-tracing-img.png"
            className="dektop-img img-responsive custom_img  about-img_odd" alt="" />

        </div>
      </div>
    </div>
  </div>
</div>

{/* <!-- About Section 5--> */}
<div className="commonAbout about-odd">
  <div className="container ">
    <div className="row">
      <div className="col-xs-12 mobile-about-text">
        <h2>Alerts</h2>
      </div>
      <div className="col-xs-12 col-md-6 col-sm-7 padRight0 mobile-about-img">
        <div className="about-img pull-right ">

          <img src="assets/images/snappyflow-alert-img.png" className="img-responsive " alt="" />
        </div>
      </div>
      <div className="col-xs-12 col-md-7 col-sm-8 about-img-wrapper">
        <div className="about-img" style={{marginTop: "-24px"}}>
          <img src="assets/images/snappyflow-alert-img.png"
            className="dektop-img img-responsive custom_img  about-img_even" alt="" />

        </div>
      </div>
      <div className="col-xs-12 col-md-5 col-sm-4 about-wrapper">
        <div className="about-text">
          <h2>Alerts</h2>
          <ul className="disc_list">
            <li>​High fidelity alerts with excellent traceability to its related metrics or logs
            </li>
            <li>Pre-built alert library and <br/>auto-recommendation</li>
            <li>Powerful language to define a wide range of alerts to cater different types of alert conditions
            </li>
            <li>Automatic grouping of alerts by sub-systems, tiers or applications leading to better abstraction
              and
              lower noise</li>
            <li>Notifications via Email, Slack, Pager Duty or Webhooks</li>
          </ul>
        </div>
        <div className="marTop25">
          <Link href="/" className="freetrial_link "> FREE TRIAL </Link>
        </div>
      </div>
    </div>
  </div>
</div>
<div className="commonAbout about">
  <div className="container">
    <div className="row">
      <div className="col-xs-12 mobile-about-text">
        <h2>Synthetics</h2>
      </div>
      <div className="col-xs-12 col-md-6 col-sm-7 padRight0 mobile-about-img">
        <div className="about-img pull-right ">

          <img src="assets/images/synthetic.png" className="img-responsive " alt="" />
        </div>
      </div>
      <div className="col-xs-12 col-md-5 col-sm-4 about-wrapper">
        <div className="about-text">
          <h2>Synthetics</h2>
          <ul className="disc_list">
            <li>​Monitor availability and response times of API end-points
            </li>
            <li>Provision workloads easily with sfPoller module either locally or globally using lambda functions
            </li>
            <li>View dashboards or configure alerts in SnappyFlow SaaS or Appliance
            </li>
            <li>Pricing based on size of data managed rather than workload frequencies
            </li>

          </ul>
        </div>
        <div className="marTop25">
          <Link href="/" className="freetrial_link "> FREE TRIAL </Link>
        </div>
      </div>
      <div className="col-xs-12 col-md-7 col-sm-8 about-img-wrapper ">
        <div className="about-img marTop_5">
          <img src="assets/images/synthetic.png" className="dektop-img img-responsive custom_img about-img_odd" alt="" />

        </div>
      </div>
    </div>
  </div>
</div>


<div className="commonAbout integration_bg">
  <div className="container padLeft0 padRight0">
    <div className="about-text ">
      <h2 className="marTop50" style={{position: "relative", top: "-30px",  textAlign: 'center', display: "block"}}>Integrations</h2>
    </div>
    <div className="clear">
      <div className="">
        <div className="">
          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/Amazon_Cloudwatch.jpg" className="img-responsive img-integration" alt="" />
          </div>
          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/amazon_dynamoDB.jpg" className="img-responsive img-integration" alt="" />
          </div>
          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/amazon_ebs.jpg" className="img-responsive img-integration" alt="" />
          </div>
          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/amazonec2.jpg" className="img-responsive img-integration" alt="" />

          </div>
          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/amazonelb.jpg" className="img-responsive img-integration" alt="" />

          </div>

          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/Amazon_RDS.jpg" className="img-responsive img-integration" alt="" />
          </div>
          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/amazon_s3.jpg" className="img-responsive img-integration" alt="" />
          </div>

          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/amazon-api-gateway.jpg" className="img-responsive img-integration" alt="" />
          </div>
          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/apache.jpg" className="img-responsive img-integration" alt="" />
          </div>
          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/aws.jpg" className="img-responsive img-integration" alt="" />
          </div>


          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/ansible.jpg" className="img-responsive img-integration" alt="" />
          </div>
          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/Apache-Spark.jpg" className="img-responsive img-integration" alt="" />

          </div>

          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/Apache-Tomcat.jpg" className="img-responsive img-integration" alt="" />
          </div>
          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/aws_ecs.jpg" className="img-responsive img-integration" alt="" />
          </div>
          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/AWS_EKS.jpg" className="img-responsive img-integration" alt="" />
          </div>
          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/AWS_VMware.jpg" className="img-responsive img-integration" alt="" />

          </div>
          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/azure.jpg" className="img-responsive img-integration" alt="" />
          </div>
          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/cassandra.jpg" className="img-responsive img-integration" alt="" />
          </div>
          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/centos.jpg" className="img-responsive img-integration" alt="" />
          </div>


          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/debian.jpg" className="img-responsive img-integration" alt="" />
          </div>
          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/docker.jpg" className="img-responsive img-integration" alt="" />

          </div>
          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/elastic.jpg" className="img-responsive img-integration" alt="" />

          </div>
          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/fedora.jpg" className="img-responsive img-integration" alt="" />
          </div>
          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/google-cloud.jpg" className="img-responsive img-integration" alt="" />
          </div>
          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/hadoopNew.jpg" className="img-responsive img-integration" alt="" />
          </div>
          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/HAProxy.jpg" className="img-responsive img-integration" alt="" />
          </div>
          {/*   <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
        <img src="assets/images/java.jpg" className="img-responsive img-integration" alt="" />
      </div> */}
          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/java-JMX.jpg" className="img-responsive img-integration" alt="" />
          </div>


          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/jenkis.jpg" className="img-responsive img-integration" alt="" />
          </div>
          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/jmeter.jpg" className="img-responsive img-integration" alt="" />
          </div>
          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/kaf.jpg" className="img-responsive img-integration" alt="" />
          </div>
          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/kubernetes.jpg" className="img-responsive img-integration" alt="" />
          </div>
          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/linux.jpg" className="img-responsive img-integration" alt="" />
          </div>
          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/microsoft-sql-server.jpg" className="img-responsive img-integration" alt="" />
          </div>
          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/mongodb.jpg" className="img-responsive img-integration" alt="" />
          </div>
          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/my_sql.jpg" className="img-responsive img-integration" alt="" />
          </div>

          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/nginx_new.jpg" className="img-responsive img-integration" alt="" />
          </div>
          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/nodejs.jpg" className="img-responsive img-integration" alt="" />
          </div>
          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/nutanix.jpg" className="img-responsive img-integration" alt="" />
          </div>
          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/oracle-database.jpg" className="img-responsive img-integration"
              alt="" />
          </div>
          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/post_gresql.jpg" className="img-responsive img-integration" alt="" />
          </div>
          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/puppet.jpg" className="img-responsive img-integration" alt="" />
          </div>
          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/python.jpg" className="img-responsive img-integration" alt="" />
          </div>


          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/redis.jpg" className="img-responsive img-integration" alt="" />
          </div>
          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/redhat.jpg" className="img-responsive img-integration" alt="" />
          </div>
          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/slack.jpg" className="img-responsive img-integration" alt="" />
          </div>
          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/suse.jpg" className="img-responsive img-integration" alt="" />
          </div>
          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/ubuntu.jpg" className="img-responsive img-integration" alt="" />
          </div>

          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/vmware.jpg" className="img-responsive img-integration" alt="" />
          </div>

          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/vpc.jpg" className="img-responsive img-integration" alt="" />
          </div>

          <div className="col-sm-3 col-xs-6 col-md-2 about-img-border">
            <img src="assets/images/windows.jpg" className="img-responsive img-integration" alt="" />
          </div>


        </div>

      </div>
    </div>

  </div>
</div>
<style jsx>
  {
    `
  .product-intro {
      background: #f8f8f8;
      width: 100%;
      height: 550px;
  }
   
  .productContainer {
     padding: 120px 0;
  }
  .intro-text{
    color: #fff;
      font-size: 18px;
      line-height: 24px;
      font-weight: normal; 
  }
  .intro-text p{
      font-size: 24px;
      padding: 4px 75px;
      line-height: 30px;
  }
  .free_trial_link  {
      position: relative;
      top: 15px;
      color: #009dd0;
      font-size: 16px;
  }
  .product-intro ul {
      padding: 10px 0 0px 0;
   
  }

  .content {
    font-size: 44px; 
    padding-top:  7%;
    font-weight: 600;
    text-align: left;
  }
  .content h1{
    color: #2A383B;
    text-align: left;
    letter-spacing: 0.24px;
    font-weight: 700 !important;
    font-size: 48px;
  }
  .content h1 label{
    font-size: 48px;
    font-family: Lato-Light;
    font-weight: 300;
  }
  .content h5{
    color: #2A383B;
     font-weight: 500;
      font-size: 24px;
      margin-top: 15px;
      line-height: 34px;
      text-align: left;
      letter-spacing: 0.7px;
  }
  .content-header-inner {
    position: absolute;
    top: 18%;
    left: 0px;
    font-size: 30px;
    color: #363c44;
    letter-spacing: 0.9px;
  }
  .content-header-inner-h5 {
    position: absolute;
    top: 15%;
    left: 0px;
    font-size: 18px;
    font-weight: normal;
    font-stretch: normal;
    font-style: normal;
    line-height: normal;
    letter-spacing: 0.6px;
    text-align: left;
    color: #363c44;
    text-transform: none;
  }
  
  .about-header{
      padding: 40px;
  
  }
  
  .content-wrapper{
    display: flex;
  }
  
  .gapdiv{
      width: 0% !important;;
  }
  .tick-img2{
      margin-top: 5px;
  }
  
  .disc_list li{
      color: #363c44;
      font-size: 20px;
      line-height: 28px;
      
  }
  .deploymentModalWrapper:hover{
      background-color: #316984;  
  
  }
  .deploymentModalWrapper{
      background-color:#3887ad;
      color:white;
      cursor: pointer;
  }
  .topText{
      position: fixed;
      bottom: 100px;
      display: none;
      right: 10px;
  }
  
  .featuresDivInner{
      height: 91px;
      border-radius: 12px;
      border: solid 1px rgba(165, 162, 162, 0.15);
      background-color: #fbfbfb;
      cursor: pointer;
  }
  .featuresDivInner:hover{
      background-color: #fff;
      box-shadow: 0 0 16px 0 rgba(0, 0, 0, 0.1);
  }
  .featuresDivDetail{
      font-weight: 500;   
      font-size: 22px; 
      font-stretch: normal;
      font-style: normal;
      line-height: normal;
      letter-spacing: 0.18px;
      text-align: left;
      float: left;
      color: #363c44;
      margin-top: 30px;
      margin-left: 15px;
      
  }
  .panel_divided{
      margin-bottom: 15px;
      padding-right: 2px;
  }
  .featureImg{
      padding: 17px 0 0 38px;
      float: left;
  }
  .about-text-inner-detail{
      margin-left: 20px;
      padding: 0px 2px 15px 2px;
  }
  .about-wrapper .about-text{
      margin-top: unset;
  }
  .pad_bottom7{
      padding-bottom: 7px;
  }

  .leftContainer{
   padding-left: 0;   
   margin-left: 0;
  }
  .rightContainer{
      padding-right: 0;
      margin-right: 0 ;
  }
  .mobile-about-text{
      display: none;
  }
  .about-text h2{
      font-weight: 700;
      color: #2A383B;
      font-size: 36px;
      margin-bottom: 30px !important;
      text-transform: unset;
      margin-bottom: 15px;
  }
  .server_img_product {
    background: transparent url('assets/images/product-page-bannner_new.png') 0px 3px no-repeat;
    height: 390px;
  }
  .intergration_panel{
      text-align: left;
      padding: 25px;
      font-weight: 500; 
      border-radius: 2.5px;
      border-radius: 2px;
      box-shadow: 1px 2px 11px #dadada;
      background-color: #ffffff; 
      border: 1px solid #ddd;
  }
  .intergration_panel img{
      margin-bottom: 20px;
  }
  .img-integration{
      margin: 0px 0px 15px 0px;
      border-radius: 5px;
      box-shadow: 0 0 3px 0 rgba(0, 0, 0, 0.15);
      background-color: #ffffff;
  } 
  .about-img-border  {
      padding: 5px 8px;
  }
  .mobile-about-img{
      display: none;
  }
  @media screen and (max-width: 767px) and (min-width: 320px){
    .server_img_product{
      background-size: 100%;
      background-position: center 50%;
    }
      .product-intro{
          position: relative !important;
          height: 250px !important;
      
      }
      .intro-text{
          padding: unset !important;
          position: unset;
          top: unset;
      }
   
      .featuresDiv .container .row .panel_divided{
          padding-right:15px !important;
      }
      .mobile-about-text{
          display: block;
          padding-left: 8% !important;
      }
      .about-text h2{
          display: none;
      }
      .mobile-about-text h2{
          color: #2A383B !important;
          font-size: 36px;
          text-align: center;
      }
      .about-text ul{
          padding: 10px 2px 10px 30px !important;
      }
      .about-wrapper .marTop25{
        text-align: center;
        margin-top: 10px !important;
      }
      .content h1{
          text-align: center !important;
      }
      .content{
          padding-top: 0 !important;
      }
      .content h5{
          padding-right: 0 !important;
          text-align: center;
      }
      .about-text h2,
      .content-header-inner,
      .content-header-inner-h5,
      .dektop-img {
        display: none;
      }
      .mobile-about-img{
          display: block;
      }
  }
  @media only screen and (max-width: 419px) and (min-width: 300px){
       
      .featuresDiv .container .row .panel_divided{
          padding-right:15px !important;
      }
  }
  
  @media only screen and  (max-width: 356px){
      .featuresDivDetail{
          font-size: 14px !important;
      }
  }
  @media screen and (max-width: 990px) and (min-width: 768px) {
      header{
          margin-top: 56px !important;
      }
      .product-intro{
          position: relative !important;
          height: 250px !important;
      
      }
      .intro-text{
          padding: unset !important;
          position: unset;
          top: unset;
      } 
  }
    `
  }
</style>
</Layout>
    </div>
  )
}
