import Head from 'next/head'
import Image from 'next/image'
import Layout from '../components/Layout'
import Link from "next/link";
import styles from '../styles/Home.module.css'

export default function Team() {
  return (
    <div className='teams-page'>
      <Head>
        <title>Team</title>
        <meta name="description" content="Generated by suraj" />
        <link rel="icon" href="/favicon.ico" />
		<link rel="canonical" href="https://snappyflow-test.surge.sh/team" />
        <meta property="og:title" content="Snappyflow - Team" />
        <meta property="og:type" content="Snappyflow - Team" />
        <meta property="og:description" name="description" content="Snappyflow - Team" />
        <meta property="og:url" content="/team" key="ogurl" />
        <meta property="og:image" content="assets/images/add-application-screen.png" key="ogimage" />
      </Head>

      <Layout>
      <header id="freetrial-header">
	<div className="team-intro indexDiv">
	  <div className="freetrial-overlay">
		<div className="container">
		  <div className="row">
			<div className="intro-text container">
			  <div className="row">
				<div className="col-md-6 col-xs-12 position_unset ">
				  <div className="content">
					<h1>Meet <label>the</label> <br /> Leadership Team</h1>
				  </div>
				</div>
				<div className="col-md-6 col-xs-12 position_unset">
				  <div className="server_img1"> </div>
				</div>
			  </div>
			</div>
		  </div>
		 
		</div>
	  </div>
	</div>
  
  </header>
  <div className="commonAbout about">
	<div className="container">
	  <div className="row">
		<div className="col-md-4 col-xs-12 team-member-padding">
		  <div className="card">
			<img
			  className="card-img-top img-responsive"
			  src="assets/images/pramod-murthy-pic.jpg"
			  alt="Card image cap"
			/>
			<div className="card-body">
			  <h4 className="card-title">Pramod Murthy</h4>
			  <div className="paddingTop10 team-designation">
				Co-Founder & <br />
				Head of Products & Solutions
			  </div>
			  <div className="clear marTop25">
				<Link
				href="http://linkedin.com/in/pramod-m-727b09"
				  ><img
					className="img-arrow"
					src="assets/images/linkedin-icon-team.png"
                    alt="linkedIn Pramod Murthy"
				/></Link>
			  </div>
			</div>
		  </div>
		</div>
  
		<div className="col-md-4 col-xs-12 team-member-padding">
		  <div className="card">
			<img
			  className="card-img-top img-responsive"
			  src="assets/images/sreeni-potluri-pic.jpg"
			  alt="Card image cap"
			/>
			<div className="card-body">
			  <h4 className="card-title">Sreeni Potluri</h4>
			  <div className="paddingTop10 team-designation">
				Co-Founder & <br />Head of Sales & Biz Dev
			  </div>
			  <div className="clear marTop25">
				<Link
				href="http://linkedin.com/in/sreeni-potluri-49832b4"
				  ><img
					className="img-arrow"
					src="assets/images/linkedin-icon-team.png"
                    alt="linkedIn Sreeni Potluri"
				/></Link>
			  </div>
			</div>
		  </div>
		</div>
		<div className="col-md-4 col-xs-12 team-member-padding">
			<div className="card">
			  <img
				className="card-img-top img-responsive"
				src="assets/images/srivathsa-mugalodi-pic.jpg"
				alt="Card image cap"
			  />
			  <div className="card-body">
				<h4 className="card-title">Srivathsa Mugalodi</h4>
				<div className="paddingTop10 team-designation">
				 Head of <br /> India Engineering Center
				</div>
				<div className="clear marTop25">
					<Link
					 href="http://linkedin.com/in/srivathsa-m-9147111"
					  ><img
						className="img-arrow"
						src="assets/images/linkedin-icon-team.png"
                        alt="linkedIn Srivathsa Mugalodi"
					/></Link>
				  </div>
			  </div>
			</div>
		  </div>
	  </div>
	 
	</div>
	<div className="outer_advisors_row">
		<div className="container">
		 <div className="row">
		  	<div className="col-md-4 col-xs-12">&nbsp;</div>
		  	<div className="col-md-4 col-xs-12 team-member-padding">
		  		<h4 className="text-center title_advisor">Advisors</h4>
			  <div className="card brd_0"> 
				<img
				  className="card-img-top img-responsive"
				  src="assets/images/bill-gargiulo-adviser.png"
				  alt="Card image cap"
				/>
				<div className="card-body">
				  <h4 className="card-title">Bill Gargiulo</h4>
				  <div className="paddingTop10 team-designation">
					Technical Advisor 
				  </div>
				  <div className="clear marTop25">
					<Link
					href="https://www.linkedin.com/in/billgargiulo/"
					  ><img
						className="img-arrow"
						src="assets/images/linkedin-icon-team.png"
                        alt="linkedIn Bill Gargiulo"
					/></Link>
				  </div>
				</div>
				</div>
			  </div>
		</div>
	  </div>
	</div>
  </div>
  <style jsx>
	  {`
	 	.team {
			padding: 120px 0;
			/*background: red*/
		}
		.team h3 {
			font-size: 30px;
			font-weight: bold;
			text-align: center;
			height: 65px;
		}
		.team .about-text {
			margin-left: 10px;
			text-align: center;
		}
		.team .about-img {
			display: block;
			position: relative;
		}
		.team p {
			line-height: 16px;
			line-height: 24px;
			margin: 15px 0 15px;
			text-align: center;
		}
		
		.mobileAboutText {
			display: none;
		}
		
		.card {
			border-radius: 5px;
			border: 1px solid #f0f0f0;
			background-color: #ffffff;
			margin-bottom: 15px;
		  }
		  .card-body h4 {
			font-size: 24px;
			font-family: Lato-Bold !important;
			font-weight: 600;
			font-stretch: normal;
			font-style: normal;
			margin-bottom: 15px;
			line-height: normal;
			letter-spacing: normal;
			text-align: center;
			color: #2a383b;
			text-transform: unset;
		  }
		  .card-body {
			padding:0px 30px 30px;
			text-align: center;
		  }
		  .card-body .team-designation{
			  color: #23b5e9;
			  font-size: 16px;
		  }
		  .card-img-top{
			  padding: 9px;
			  width: 100%;
		  }
		  .team-intro {
			background: #f8f8f8;
			width: 100%;
			height: 550px;
		}
		.server_img1{
			background: transparent url(assets/images/team-header-image.png) 55% 50px no-repeat;
			height: 400px; 
		}
		.indexDiv .intro-text{ 
			text-align: center;
			font-size: 20px;
			line-height: 34px; 
			height: 538px;
		}
		.content h1 label{
			font-size: 48px;
			font-family: Lato-Light;
			font-weight: 300;
		}
		.position_unset{
			position: unset;
		}
		.content h1{
			color: #2A383B;
			text-align: left;
			letter-spacing: 0.24px;
			font-size: 48px;
		}
		.content {
			font-size: 44px;
			padding-top: 8.2%;
			font-weight: 600;
			text-align: left;
		}
		.team-member-padding{
			padding-left: 18.5px !important;
			padding-right: 18.5px !important;
		}
		.outer_advisors_row{
			background: #f9f9f9;
			padding: 15px 0px;
			margin: 20px 0px;
		}
		.title_advisor{
			font-size: 25px;
			font-weight: bold;
			padding: 20px;
			margin-bottom: 0px;
			text-transform: capitalize;
		}
			@media only screen and (min-width: 320px) and (max-width: 767px) {
				.intro-text{
					padding: unset !important;
					position: unset;
					top: unset;
				}
				.intro-text h1{
					font-size: 36px !important;
					line-height: 36px !important;
					left: 8% !important;
					top: 55% !important;
					/*width: 41% !important;*/
					text-align: left;
				}
				.about-text{
					text-align: center;
				}
				.mobileAboutText {
					display: block;
				}
				.desktopAboutText{
					display: none;
				} 
				.mobileAboutText .about-text h2{
					color:#363c44;
				}
				.img-responsive{
					  display: unset;
				  }
				  .col-xs-12{
					  text-align: center;
				  }
			  }
			  @media screen and (max-width: 990px) and (min-width: 768px) {
				  .col-xs-12{
					  text-align: center;
				  }
				  .img-responsive{
					  display: unset;
				  }
				header{
					margin-top: 56px !important;
				}
				.intro-text{
					padding: unset !important;
					position: unset;
					top: unset;
				}
				.intro-text h1{
					font-size: 21px !important;
					line-height: 36px !important;
					left: 8% !important;
					top: 55% !important;
					width: 41% !important;
					text-align: left;
				}
				.team-intro{
					position: relative !important;
					height: 243px !important;
				}
			  } 
	  `}
  </style>
      </Layout>
    </div>
  )
}
