import Head from 'next/head'
import Link from 'next/link'
import Layout from '../components/Layout'

export default function Terms() {
  return (
    <div className='terms-page'>
      <Head>
        <title>Terms</title>
        <meta name="description" content="Generated by suraj" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
      <div className="commonAbout about2">
        <div className="container">
            <div className="row">
            <div className="col-md-12 col-xs-12">
                <div className="center">
                    <h2>Terms of Use</h2> 
                    </div>
                    <div className="terms-head">
                    <h4>Rules and Regulations</h4>
                    <p>The following rules and regulations apply to all visitors to or users of this Web Site. By accessing this Web Site, user acknowledges acceptance of these terms and conditions. MapleLabs Inc (&quot;MapleLabs&quot;) reserves the right to change these rules and regulations from time to time at its sole discretion. In the case of any violation of these rules and regulations, MapleLabs reserves the right to seek all remedies available by law. These rules and regulations apply to all visits to the MapleLabs Web Site, both now and in the future.
                    </p>
                </div>
                <div className="terms-head">
                    <h4>Limited License</h4>
                    <p> 
                        MapleLabs hereby authorizes you to copy materials published by MapleLabs on this Web Site solely for non-commercial use within your organization in support of MapleLabs products. No other use of the information is authorized. In consideration of this authorization, you agree that any copy of these materials which you make shall retain all copyright and other proprietary notices in the same form and manner as on the original. Except as specified above, nothing contained herein shall be construed as conferring by implication, estoppel or otherwise any license or right under any patent, trademark or copyright of MapleLabs or any third party. ALL CONTENTS ON THIS SITE ARE PROTECTED BY COPYRIGHT. EXCEPT AS SPECIFICALLY PERMITTED HEREIN, NO PORTION OF THE INFORMATION ON THIS WEB SITE MAY BE REPRODUCED IN ANY FORM, OR BY ANY MEANS, WITHOUT PRIOR WRITTEN PERMISSION FROM MAPLELABS. VISITORS OR USERS ARE NOT PERMITTED TO MODIFY, DISTRIBUTE, PUBLISH, TRANSMIT OR CREATE DERIVATIVE WORKS OF ANY MATERIAL FOUND ON THIS SITE FOR ANY PUBLIC OR COMMERCIAL PURPOSES.
                    </p>
                </div>
                <div className="terms-head">
                    <h4>Compliance With Applicable Laws, Export Control Laws</h4>
                    <p> 
                        User access to this Web Site is governed by all applicable federal, state and local laws. All information available on the Web Site is subject to U.S. export control laws and may also be subject to the laws of the country where you reside.
                    </p>
                </div>
                <div className="terms-head">
                    <h4>Trademarks</h4>
                    <p> 
                        The trademarks, logos and service marks (&quot;Marks&quot;) displayed on this Web Site are the property of MapleLabs or other third parties. Users are not permitted to use these Marks without the prior written consent of MapleLabs or such third party which may own the Mark. &quot;MapleLabs&quot; is a registered trademark of MapleLabs Inc.
                    </p>
                </div>
                
                <div className="terms-head">
                    <h4>General Disclaimer</h4>
                    <p> 
                        Although MapleLabs has attempted to provide accurate information on the Web Site, MapleLabs assumes no responsibility for the accuracy of the information. MapleLabs may change the programs or services mentioned at any time without notice. Mention of non-MapleLabs products or services is for information purposes only and constitutes neither an endorsement nor a recommendation. ALL INFORMATION PROVIDED ON THIS WEB SITE IS PROVIDED &quot;AS IS&quot; WITH ALL FAULTS WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED. MAPLELABS AND ITS SUPPLIERS DISCLAIM ALL WARRANTIES, EXPRESSED OR IMPLIED INCLUDING, WITHOUT LIMITATION, THOSE OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OR ARISING FROM A COURSE OF DEALING, USAGE, OR TRADE PRACTICE. MAPLELABS AND ITS SUPPLIERS SHALL NOT BE LIABLE FOR ANY INDIRECT, SPECIAL, CONSEQUENTIAL, OR INCIDENTAL DAMAGES INCLUDING, WITHOUT LIMITATION, LOST PROFITS OR REVENUES, COSTS OF REPLACEMENT GOODS, LOSS OR DAMAGE TO DATA ARISING OUT OF THE USE OR INABILITY TO USE THIS SITE OR ANY MAPLELABS SERVICE, DAMAGES RESULTING FROM USE OF OR RELIANCE ON THE INFORMATION PRESENT, EVEN IF MAPLELABS OR ITS SUPPLIERS HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
                    </p>
                </div>
                <div className="terms-head">
                    <h4>Links to Third Party Sites</h4>
                    <p> 
                        This Web Site may contain links to third party sites. Access to any other Internet site linked to this Web Site is at the user&apos;s own risk and MapleLabs is not responsible for the accuracy or reliability of any information, data, opinions, advice or statements made on these sites. MapleLabs provides these links merely as a convenience and the inclusion of such links does not imply an endorsement.
                    </p>
                </div>
                <div className="terms-head">
                    <h4>User&apos;s Right to Privacy</h4>
                    <p> 
                        The User&apos;s right to privacy is of paramount importance to MapleLabs. Any information provided by the User will not be shared with any third party. MapleLabs reserves the right to use the information to provide the User a more personalized online experience.
                    </p>
                </div>
                

            </div>
            </div> 
        </div>
        </div>
        <style jsx>
            {`
                .center{
                    text-align: center;
                    font-weight: bold;
                }
                .container {
                    width: 1000px;
                }
                
                h2{
                    padding-bottom: 50px;
                }
                .center h2{
                    color: #009ece; 
                }
                .terms-head h4{
                    text-transform: none;
                    font-weight: unset;
                    font-size: 20px;
                    padding-top: 15px;
                    padding-bottom: 10px;
                    font-family: Lato-Semibold;
                }
                .terms-head{
                    margin-bottom: 20px;
                }
                h2{
                    padding-bottom: 50px;
                    text-transform:  unset;
                }
            `}
        </style>
      </Layout>
    </div>
  )
}
